# easy_bimeh_landing
#
# This file was automatically generated by APIMATIC
# v2.0 ( https://apimatic.io ).

module EasyBimehLanding
  # DamageType Model.
  class DamageType < BaseModel
    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :title

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :sort_priority

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :create_on

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :update_on

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :created_by

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :updated_by

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :create_on_persian_date

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :update_on_persian_date

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['id'] = 'id'
      @_hash['title'] = 'title'
      @_hash['sort_priority'] = 'sortPriority'
      @_hash['create_on'] = 'createOn'
      @_hash['update_on'] = 'updateOn'
      @_hash['created_by'] = 'createdBy'
      @_hash['updated_by'] = 'updatedBy'
      @_hash['create_on_persian_date'] = 'createOnPersianDate'
      @_hash['update_on_persian_date'] = 'updateOnPersianDate'
      @_hash
    end

    def initialize(id = nil,
                   title = nil,
                   create_on = nil,
                   update_on = nil,
                   created_by = nil,
                   create_on_persian_date = nil,
                   update_on_persian_date = nil,
                   sort_priority = nil,
                   updated_by = nil)
      @id = id
      @title = title
      @sort_priority = sort_priority
      @create_on = create_on
      @update_on = update_on
      @created_by = created_by
      @updated_by = updated_by
      @create_on_persian_date = create_on_persian_date
      @update_on_persian_date = update_on_persian_date
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      id = hash['id']
      title = hash['title']
      create_on = hash['createOn']
      update_on = hash['updateOn']
      created_by = hash['createdBy']
      create_on_persian_date = hash['createOnPersianDate']
      update_on_persian_date = hash['updateOnPersianDate']
      sort_priority = hash['sortPriority']
      updated_by = hash['updatedBy']

      # Create object from extracted values.
      DamageType.new(id,
                     title,
                     create_on,
                     update_on,
                     created_by,
                     create_on_persian_date,
                     update_on_persian_date,
                     sort_priority,
                     updated_by)
    end
  end
end
