# easy_bimeh_landing
#
# This file was automatically generated by APIMATIC
# v2.0 ( https://apimatic.io ).

module EasyBimehLanding
  # ElectronicEquipmentInsurancePolicyExtendView Model.
  class ElectronicEquipmentInsurancePolicyExtendView < BaseModel
    # شناسه ی نوع دستگاه
    # @return [Integer]
    attr_accessor :device_type_id

    # شناسه ی برند دستگاه
    # @return [Integer]
    attr_accessor :device_brand_id

    # شناسه ی مدل دستگاه
    # @return [Integer]
    attr_accessor :device_model_id

    # سریال دستگاه
    # @return [String]
    attr_accessor :device_serial

    # سال ساخت دستگاه
    # @return [String]
    attr_accessor :build_year

    # سال ساخت دستگاه
    # @return [Integer]
    attr_accessor :device_value

    # سال ساخت دستگاه
    # @return [Integer]
    attr_accessor :franchisee

    # سال ساخت دستگاه
    # @return [Boolean]
    attr_accessor :has_warranty

    # سال ساخت دستگاه
    # @return [String]
    attr_accessor :warranty_company

    # سال ساخت دستگاه
    # @return [String]
    attr_accessor :serial_insurance_card

    # سال ساخت دستگاه
    # @return [Long]
    attr_accessor :meta_media_behind_device_id

    # سال ساخت دستگاه
    # @return [String]
    attr_accessor :meta_media_behind_device_url

    # سال ساخت دستگاه
    # @return [Long]
    attr_accessor :meta_media_on_device_id

    # سال ساخت دستگاه
    # @return [String]
    attr_accessor :meta_media_on_device_url

    # سال ساخت دستگاه
    # @return [Long]
    attr_accessor :meta_media_device_box_id

    # سال ساخت دستگاه
    # @return [String]
    attr_accessor :meta_media_device_box_url

    # سال ساخت دستگاه
    # @return [String]
    attr_accessor :insurance_coverage_ids

    # سال ساخت دستگاه
    # @return [String]
    attr_accessor :insurance_coverage_price

    # سال ساخت دستگاه
    # @return [String]
    attr_accessor :base_premium

    # سال ساخت دستگاه
    # @return [String]
    attr_accessor :all_premium

    # سال ساخت دستگاه
    # @return [String]
    attr_accessor :insurance_company_discount_rate

    # سال ساخت دستگاه
    # @return [Integer]
    attr_accessor :insurance_company_discount

    # سال ساخت دستگاه
    # @return [Integer]
    attr_accessor :insurance_centre_discount

    # سال ساخت دستگاه
    # @return [Integer]
    attr_accessor :coupen_discount

    # سال ساخت دستگاه
    # @return [Integer]
    attr_accessor :all_discount

    # سال ساخت دستگاه
    # @return [Integer]
    attr_accessor :exchange_premium

    # سال ساخت دستگاه
    # @return [String]
    attr_accessor :device_type_title

    # سال ساخت دستگاه
    # @return [String]
    attr_accessor :device_brand_title

    # سال ساخت دستگاه
    # @return [String]
    attr_accessor :device_model_title

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['device_type_id'] = 'deviceTypeId'
      @_hash['device_brand_id'] = 'deviceBrandId'
      @_hash['device_model_id'] = 'deviceModelId'
      @_hash['device_serial'] = 'deviceSerial'
      @_hash['build_year'] = 'buildYear'
      @_hash['device_value'] = 'deviceValue'
      @_hash['franchisee'] = 'franchisee'
      @_hash['has_warranty'] = 'hasWarranty'
      @_hash['warranty_company'] = 'warrantyCompany'
      @_hash['serial_insurance_card'] = 'serialInsuranceCard'
      @_hash['meta_media_behind_device_id'] = 'metaMediaBehindDeviceId'
      @_hash['meta_media_behind_device_url'] = 'metaMediaBehindDeviceUrl'
      @_hash['meta_media_on_device_id'] = 'metaMediaOnDeviceId'
      @_hash['meta_media_on_device_url'] = 'metaMediaOnDeviceUrl'
      @_hash['meta_media_device_box_id'] = 'metaMediaDeviceBoxId'
      @_hash['meta_media_device_box_url'] = 'metaMediaDeviceBoxUrl'
      @_hash['insurance_coverage_ids'] = '_InsuranceCoverageIds'
      @_hash['insurance_coverage_price'] = 'insuranceCoveragePrice'
      @_hash['base_premium'] = 'basePremium'
      @_hash['all_premium'] = 'allPremium'
      @_hash['insurance_company_discount_rate'] =
        'insuranceCompanyDiscountRate'
      @_hash['insurance_company_discount'] = 'insuranceCompanyDiscount'
      @_hash['insurance_centre_discount'] = 'insuranceCentreDiscount'
      @_hash['coupen_discount'] = 'coupenDiscount'
      @_hash['all_discount'] = 'allDiscount'
      @_hash['exchange_premium'] = 'exchangePremium'
      @_hash['device_type_title'] = 'deviceTypeTitle'
      @_hash['device_brand_title'] = 'deviceBrandTitle'
      @_hash['device_model_title'] = 'deviceModelTitle'
      @_hash
    end

    def initialize(insurance_company_discount_rate = nil,
                   insurance_company_discount = nil,
                   insurance_centre_discount = nil,
                   coupen_discount = nil,
                   all_discount = nil,
                   exchange_premium = nil,
                   device_type_id = nil,
                   device_brand_id = nil,
                   device_model_id = nil,
                   device_serial = nil,
                   build_year = nil,
                   device_value = nil,
                   franchisee = nil,
                   has_warranty = nil,
                   warranty_company = nil,
                   serial_insurance_card = nil,
                   meta_media_behind_device_id = nil,
                   meta_media_behind_device_url = nil,
                   meta_media_on_device_id = nil,
                   meta_media_on_device_url = nil,
                   meta_media_device_box_id = nil,
                   meta_media_device_box_url = nil,
                   insurance_coverage_ids = nil,
                   insurance_coverage_price = nil,
                   base_premium = nil,
                   all_premium = nil,
                   device_type_title = nil,
                   device_brand_title = nil,
                   device_model_title = nil)
      @device_type_id = device_type_id
      @device_brand_id = device_brand_id
      @device_model_id = device_model_id
      @device_serial = device_serial
      @build_year = build_year
      @device_value = device_value
      @franchisee = franchisee
      @has_warranty = has_warranty
      @warranty_company = warranty_company
      @serial_insurance_card = serial_insurance_card
      @meta_media_behind_device_id = meta_media_behind_device_id
      @meta_media_behind_device_url = meta_media_behind_device_url
      @meta_media_on_device_id = meta_media_on_device_id
      @meta_media_on_device_url = meta_media_on_device_url
      @meta_media_device_box_id = meta_media_device_box_id
      @meta_media_device_box_url = meta_media_device_box_url
      @insurance_coverage_ids = insurance_coverage_ids
      @insurance_coverage_price = insurance_coverage_price
      @base_premium = base_premium
      @all_premium = all_premium
      @insurance_company_discount_rate = insurance_company_discount_rate
      @insurance_company_discount = insurance_company_discount
      @insurance_centre_discount = insurance_centre_discount
      @coupen_discount = coupen_discount
      @all_discount = all_discount
      @exchange_premium = exchange_premium
      @device_type_title = device_type_title
      @device_brand_title = device_brand_title
      @device_model_title = device_model_title
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      insurance_company_discount_rate = hash['insuranceCompanyDiscountRate']
      insurance_company_discount = hash['insuranceCompanyDiscount']
      insurance_centre_discount = hash['insuranceCentreDiscount']
      coupen_discount = hash['coupenDiscount']
      all_discount = hash['allDiscount']
      exchange_premium = hash['exchangePremium']
      device_type_id = hash['deviceTypeId']
      device_brand_id = hash['deviceBrandId']
      device_model_id = hash['deviceModelId']
      device_serial = hash['deviceSerial']
      build_year = hash['buildYear']
      device_value = hash['deviceValue']
      franchisee = hash['franchisee']
      has_warranty = hash['hasWarranty']
      warranty_company = hash['warrantyCompany']
      serial_insurance_card = hash['serialInsuranceCard']
      meta_media_behind_device_id = hash['metaMediaBehindDeviceId']
      meta_media_behind_device_url = hash['metaMediaBehindDeviceUrl']
      meta_media_on_device_id = hash['metaMediaOnDeviceId']
      meta_media_on_device_url = hash['metaMediaOnDeviceUrl']
      meta_media_device_box_id = hash['metaMediaDeviceBoxId']
      meta_media_device_box_url = hash['metaMediaDeviceBoxUrl']
      insurance_coverage_ids = hash['_InsuranceCoverageIds']
      insurance_coverage_price = hash['insuranceCoveragePrice']
      base_premium = hash['basePremium']
      all_premium = hash['allPremium']
      device_type_title = hash['deviceTypeTitle']
      device_brand_title = hash['deviceBrandTitle']
      device_model_title = hash['deviceModelTitle']

      # Create object from extracted values.
      ElectronicEquipmentInsurancePolicyExtendView.new(insurance_company_discount_rate,
                                                       insurance_company_discount,
                                                       insurance_centre_discount,
                                                       coupen_discount,
                                                       all_discount,
                                                       exchange_premium,
                                                       device_type_id,
                                                       device_brand_id,
                                                       device_model_id,
                                                       device_serial,
                                                       build_year,
                                                       device_value,
                                                       franchisee,
                                                       has_warranty,
                                                       warranty_company,
                                                       serial_insurance_card,
                                                       meta_media_behind_device_id,
                                                       meta_media_behind_device_url,
                                                       meta_media_on_device_id,
                                                       meta_media_on_device_url,
                                                       meta_media_device_box_id,
                                                       meta_media_device_box_url,
                                                       insurance_coverage_ids,
                                                       insurance_coverage_price,
                                                       base_premium,
                                                       all_premium,
                                                       device_type_title,
                                                       device_brand_title,
                                                       device_model_title)
    end
  end
end
