# easy_bimeh_landing
#
# This file was automatically generated by APIMATIC
# v2.0 ( https://apimatic.io ).

module EasyBimehLanding
  # ElectronicEquipmentInsurancePolicyFilter Model.
  class ElectronicEquipmentInsurancePolicyFilter < BaseModel
    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :device_type_id

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :device_brand_id

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :device_model_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :build_year

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :device_value

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :franchisee_id

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :insurance_extra_coverage_ids

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :policy_term_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :insurance_centre_sub_domain_name

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :insurance_centre_id

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :insurance_company_id

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :is_search_query

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :gift_code

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :customer_user_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['device_type_id'] = 'deviceTypeId'
      @_hash['device_brand_id'] = 'deviceBrandId'
      @_hash['device_model_id'] = 'deviceModelId'
      @_hash['build_year'] = 'buildYear'
      @_hash['device_value'] = 'deviceValue'
      @_hash['franchisee_id'] = 'franchiseeId'
      @_hash['insurance_extra_coverage_ids'] = 'insuranceExtraCoverageIds'
      @_hash['policy_term_id'] = 'policyTermId'
      @_hash['insurance_centre_sub_domain_name'] =
        'insuranceCentreSubDomainName'
      @_hash['insurance_centre_id'] = 'insuranceCentreId'
      @_hash['insurance_company_id'] = 'insuranceCompanyId'
      @_hash['is_search_query'] = 'isSearchQuery'
      @_hash['gift_code'] = 'giftCode'
      @_hash['customer_user_id'] = 'customerUserId'
      @_hash
    end

    def initialize(is_search_query = nil,
                   device_type_id = nil,
                   device_brand_id = nil,
                   device_model_id = nil,
                   build_year = nil,
                   device_value = nil,
                   franchisee_id = nil,
                   insurance_extra_coverage_ids = nil,
                   policy_term_id = nil,
                   insurance_centre_sub_domain_name = nil,
                   insurance_centre_id = nil,
                   insurance_company_id = nil,
                   gift_code = nil,
                   customer_user_id = nil)
      @device_type_id = device_type_id
      @device_brand_id = device_brand_id
      @device_model_id = device_model_id
      @build_year = build_year
      @device_value = device_value
      @franchisee_id = franchisee_id
      @insurance_extra_coverage_ids = insurance_extra_coverage_ids
      @policy_term_id = policy_term_id
      @insurance_centre_sub_domain_name = insurance_centre_sub_domain_name
      @insurance_centre_id = insurance_centre_id
      @insurance_company_id = insurance_company_id
      @is_search_query = is_search_query
      @gift_code = gift_code
      @customer_user_id = customer_user_id
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      is_search_query = hash['isSearchQuery']
      device_type_id = hash['deviceTypeId']
      device_brand_id = hash['deviceBrandId']
      device_model_id = hash['deviceModelId']
      build_year = hash['buildYear']
      device_value = hash['deviceValue']
      franchisee_id = hash['franchiseeId']
      insurance_extra_coverage_ids = hash['insuranceExtraCoverageIds']
      policy_term_id = hash['policyTermId']
      insurance_centre_sub_domain_name = hash['insuranceCentreSubDomainName']
      insurance_centre_id = hash['insuranceCentreId']
      insurance_company_id = hash['insuranceCompanyId']
      gift_code = hash['giftCode']
      customer_user_id = hash['customerUserId']

      # Create object from extracted values.
      ElectronicEquipmentInsurancePolicyFilter.new(is_search_query,
                                                   device_type_id,
                                                   device_brand_id,
                                                   device_model_id,
                                                   build_year,
                                                   device_value,
                                                   franchisee_id,
                                                   insurance_extra_coverage_ids,
                                                   policy_term_id,
                                                   insurance_centre_sub_domain_name,
                                                   insurance_centre_id,
                                                   insurance_company_id,
                                                   gift_code,
                                                   customer_user_id)
    end
  end
end
