# easy_bimeh_landing
#
# This file was automatically generated by APIMATIC
# v2.0 ( https://apimatic.io ).

module EasyBimehLanding
  # ElevatorInsurancePolicyFilter Model.
  class ElevatorInsurancePolicyFilter < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :building_use_type_param_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :elevator_type_param_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :floors

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :elevator_capacity_cargo

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :elevator_capacity

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :risk_level_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :insurance_policy_terms

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :defect_organ_coverage_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :death_capital_coverage_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :financial_coverage_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :medical_cost_coverage_id

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :owner_coverage

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :insurance_extra_coverage_ids

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :policy_term_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :insurance_centre_sub_domain_name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :insurance_centre_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :insurance_company_id

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :is_search_query

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :gift_code

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :customer_user_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['building_use_type_param_id'] = 'buildingUseTypeParamId'
      @_hash['elevator_type_param_id'] = 'elevatorTypeParamId'
      @_hash['floors'] = 'floors'
      @_hash['elevator_capacity_cargo'] = 'elevatorCapacityCargo'
      @_hash['elevator_capacity'] = 'elevatorCapacity'
      @_hash['risk_level_id'] = 'riskLevelId'
      @_hash['insurance_policy_terms'] = 'insurancePolicyTerms'
      @_hash['defect_organ_coverage_id'] = 'defectOrganCoverageId'
      @_hash['death_capital_coverage_id'] = 'deathCapitalCoverageId'
      @_hash['financial_coverage_id'] = 'financialCoverageId'
      @_hash['medical_cost_coverage_id'] = 'medicalCostCoverageId'
      @_hash['owner_coverage'] = 'ownerCoverage'
      @_hash['insurance_extra_coverage_ids'] = 'insuranceExtraCoverageIds'
      @_hash['policy_term_id'] = 'policyTermId'
      @_hash['insurance_centre_sub_domain_name'] =
        'insuranceCentreSubDomainName'
      @_hash['insurance_centre_id'] = 'insuranceCentreId'
      @_hash['insurance_company_id'] = 'insuranceCompanyId'
      @_hash['is_search_query'] = 'isSearchQuery'
      @_hash['gift_code'] = 'giftCode'
      @_hash['customer_user_id'] = 'customerUserId'
      @_hash
    end

    def initialize(owner_coverage = nil,
                   is_search_query = nil,
                   building_use_type_param_id = nil,
                   elevator_type_param_id = nil,
                   floors = nil,
                   elevator_capacity_cargo = nil,
                   elevator_capacity = nil,
                   risk_level_id = nil,
                   insurance_policy_terms = nil,
                   defect_organ_coverage_id = nil,
                   death_capital_coverage_id = nil,
                   financial_coverage_id = nil,
                   medical_cost_coverage_id = nil,
                   insurance_extra_coverage_ids = nil,
                   policy_term_id = nil,
                   insurance_centre_sub_domain_name = nil,
                   insurance_centre_id = nil,
                   insurance_company_id = nil,
                   gift_code = nil,
                   customer_user_id = nil)
      @building_use_type_param_id = building_use_type_param_id
      @elevator_type_param_id = elevator_type_param_id
      @floors = floors
      @elevator_capacity_cargo = elevator_capacity_cargo
      @elevator_capacity = elevator_capacity
      @risk_level_id = risk_level_id
      @insurance_policy_terms = insurance_policy_terms
      @defect_organ_coverage_id = defect_organ_coverage_id
      @death_capital_coverage_id = death_capital_coverage_id
      @financial_coverage_id = financial_coverage_id
      @medical_cost_coverage_id = medical_cost_coverage_id
      @owner_coverage = owner_coverage
      @insurance_extra_coverage_ids = insurance_extra_coverage_ids
      @policy_term_id = policy_term_id
      @insurance_centre_sub_domain_name = insurance_centre_sub_domain_name
      @insurance_centre_id = insurance_centre_id
      @insurance_company_id = insurance_company_id
      @is_search_query = is_search_query
      @gift_code = gift_code
      @customer_user_id = customer_user_id
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      owner_coverage = hash['ownerCoverage']
      is_search_query = hash['isSearchQuery']
      building_use_type_param_id = hash['buildingUseTypeParamId']
      elevator_type_param_id = hash['elevatorTypeParamId']
      floors = hash['floors']
      elevator_capacity_cargo = hash['elevatorCapacityCargo']
      elevator_capacity = hash['elevatorCapacity']
      risk_level_id = hash['riskLevelId']
      insurance_policy_terms = hash['insurancePolicyTerms']
      defect_organ_coverage_id = hash['defectOrganCoverageId']
      death_capital_coverage_id = hash['deathCapitalCoverageId']
      financial_coverage_id = hash['financialCoverageId']
      medical_cost_coverage_id = hash['medicalCostCoverageId']
      insurance_extra_coverage_ids = hash['insuranceExtraCoverageIds']
      policy_term_id = hash['policyTermId']
      insurance_centre_sub_domain_name = hash['insuranceCentreSubDomainName']
      insurance_centre_id = hash['insuranceCentreId']
      insurance_company_id = hash['insuranceCompanyId']
      gift_code = hash['giftCode']
      customer_user_id = hash['customerUserId']

      # Create object from extracted values.
      ElevatorInsurancePolicyFilter.new(owner_coverage,
                                        is_search_query,
                                        building_use_type_param_id,
                                        elevator_type_param_id,
                                        floors,
                                        elevator_capacity_cargo,
                                        elevator_capacity,
                                        risk_level_id,
                                        insurance_policy_terms,
                                        defect_organ_coverage_id,
                                        death_capital_coverage_id,
                                        financial_coverage_id,
                                        medical_cost_coverage_id,
                                        insurance_extra_coverage_ids,
                                        policy_term_id,
                                        insurance_centre_sub_domain_name,
                                        insurance_centre_id,
                                        insurance_company_id,
                                        gift_code,
                                        customer_user_id)
    end
  end
end
