# easy_bimeh_landing
#
# This file was automatically generated by APIMATIC
# v2.0 ( https://apimatic.io ).

module EasyBimehLanding
  # ElevatorInsurancePolicyExtendView Model.
  class ElevatorInsurancePolicyExtendView < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :building_use_type_param_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :elevator_type_param_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :floors

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :elevator_capacity

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :elevator_capacity_cargo

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :defect_organ_coverage_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :death_capital_coverage_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :financial_coverage_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :medical_cost_coverage_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :risk_level_discount_rate

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :insurance_risk_level_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :discount_rate

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :city_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :province_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :zip_code

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :address_place_building

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :owner_coverage

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :risk_level_discount

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :base_premium

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :all_premium

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :insurance_company_discount_rate

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :insurance_company_discount

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :insurance_centre_discount

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :coupen_discount

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :all_discount

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :exchange_premium

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['building_use_type_param_id'] = 'buildingUseTypeParamId'
      @_hash['elevator_type_param_id'] = 'elevatorTypeParamId'
      @_hash['floors'] = 'floors'
      @_hash['elevator_capacity'] = 'elevatorCapacity'
      @_hash['elevator_capacity_cargo'] = 'elevatorCapacityCargo'
      @_hash['defect_organ_coverage_id'] = 'defectOrganCoverageId'
      @_hash['death_capital_coverage_id'] = 'deathCapitalCoverageId'
      @_hash['financial_coverage_id'] = 'financialCoverageId'
      @_hash['medical_cost_coverage_id'] = 'medicalCostCoverageId'
      @_hash['risk_level_discount_rate'] = 'riskLevelDiscountRate'
      @_hash['insurance_risk_level_id'] = 'insuranceRiskLevelId'
      @_hash['discount_rate'] = 'discountRate'
      @_hash['city_id'] = 'cityId'
      @_hash['province_id'] = 'provinceId'
      @_hash['zip_code'] = 'zipCode'
      @_hash['address_place_building'] = 'addressPlaceBuilding'
      @_hash['owner_coverage'] = 'ownerCoverage'
      @_hash['risk_level_discount'] = 'riskLevelDiscount'
      @_hash['base_premium'] = 'basePremium'
      @_hash['all_premium'] = 'allPremium'
      @_hash['insurance_company_discount_rate'] =
        'insuranceCompanyDiscountRate'
      @_hash['insurance_company_discount'] = 'insuranceCompanyDiscount'
      @_hash['insurance_centre_discount'] = 'insuranceCentreDiscount'
      @_hash['coupen_discount'] = 'coupenDiscount'
      @_hash['all_discount'] = 'allDiscount'
      @_hash['exchange_premium'] = 'exchangePremium'
      @_hash
    end

    def initialize(owner_coverage = nil,
                   risk_level_discount = nil,
                   insurance_company_discount_rate = nil,
                   insurance_company_discount = nil,
                   insurance_centre_discount = nil,
                   coupen_discount = nil,
                   all_discount = nil,
                   exchange_premium = nil,
                   building_use_type_param_id = nil,
                   elevator_type_param_id = nil,
                   floors = nil,
                   elevator_capacity = nil,
                   elevator_capacity_cargo = nil,
                   defect_organ_coverage_id = nil,
                   death_capital_coverage_id = nil,
                   financial_coverage_id = nil,
                   medical_cost_coverage_id = nil,
                   risk_level_discount_rate = nil,
                   insurance_risk_level_id = nil,
                   discount_rate = nil,
                   city_id = nil,
                   province_id = nil,
                   zip_code = nil,
                   address_place_building = nil,
                   base_premium = nil,
                   all_premium = nil)
      @building_use_type_param_id = building_use_type_param_id
      @elevator_type_param_id = elevator_type_param_id
      @floors = floors
      @elevator_capacity = elevator_capacity
      @elevator_capacity_cargo = elevator_capacity_cargo
      @defect_organ_coverage_id = defect_organ_coverage_id
      @death_capital_coverage_id = death_capital_coverage_id
      @financial_coverage_id = financial_coverage_id
      @medical_cost_coverage_id = medical_cost_coverage_id
      @risk_level_discount_rate = risk_level_discount_rate
      @insurance_risk_level_id = insurance_risk_level_id
      @discount_rate = discount_rate
      @city_id = city_id
      @province_id = province_id
      @zip_code = zip_code
      @address_place_building = address_place_building
      @owner_coverage = owner_coverage
      @risk_level_discount = risk_level_discount
      @base_premium = base_premium
      @all_premium = all_premium
      @insurance_company_discount_rate = insurance_company_discount_rate
      @insurance_company_discount = insurance_company_discount
      @insurance_centre_discount = insurance_centre_discount
      @coupen_discount = coupen_discount
      @all_discount = all_discount
      @exchange_premium = exchange_premium
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      owner_coverage = hash['ownerCoverage']
      risk_level_discount = hash['riskLevelDiscount']
      insurance_company_discount_rate = hash['insuranceCompanyDiscountRate']
      insurance_company_discount = hash['insuranceCompanyDiscount']
      insurance_centre_discount = hash['insuranceCentreDiscount']
      coupen_discount = hash['coupenDiscount']
      all_discount = hash['allDiscount']
      exchange_premium = hash['exchangePremium']
      building_use_type_param_id = hash['buildingUseTypeParamId']
      elevator_type_param_id = hash['elevatorTypeParamId']
      floors = hash['floors']
      elevator_capacity = hash['elevatorCapacity']
      elevator_capacity_cargo = hash['elevatorCapacityCargo']
      defect_organ_coverage_id = hash['defectOrganCoverageId']
      death_capital_coverage_id = hash['deathCapitalCoverageId']
      financial_coverage_id = hash['financialCoverageId']
      medical_cost_coverage_id = hash['medicalCostCoverageId']
      risk_level_discount_rate = hash['riskLevelDiscountRate']
      insurance_risk_level_id = hash['insuranceRiskLevelId']
      discount_rate = hash['discountRate']
      city_id = hash['cityId']
      province_id = hash['provinceId']
      zip_code = hash['zipCode']
      address_place_building = hash['addressPlaceBuilding']
      base_premium = hash['basePremium']
      all_premium = hash['allPremium']

      # Create object from extracted values.
      ElevatorInsurancePolicyExtendView.new(owner_coverage,
                                            risk_level_discount,
                                            insurance_company_discount_rate,
                                            insurance_company_discount,
                                            insurance_centre_discount,
                                            coupen_discount,
                                            all_discount,
                                            exchange_premium,
                                            building_use_type_param_id,
                                            elevator_type_param_id,
                                            floors,
                                            elevator_capacity,
                                            elevator_capacity_cargo,
                                            defect_organ_coverage_id,
                                            death_capital_coverage_id,
                                            financial_coverage_id,
                                            medical_cost_coverage_id,
                                            risk_level_discount_rate,
                                            insurance_risk_level_id,
                                            discount_rate,
                                            city_id,
                                            province_id,
                                            zip_code,
                                            address_place_building,
                                            base_premium,
                                            all_premium)
    end
  end
end
