# easy_bimeh_landing
#
# This file was automatically generated by APIMATIC
# v2.0 ( https://apimatic.io ).

module EasyBimehLanding
  # EverySquareMeterCoverage Model.
  class EverySquareMeterCoverage < BaseModel
    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :id

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :fiscal_year_id

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :insurance_coverage_id

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :coverage_rial

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :coverage_euro

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :from_price

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :to_price

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :is_discount

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :coverage_value_type

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :coverage_string_value

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :insurance_type_ids

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :insurance_company_ids

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :selected

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :is_visible

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :insurance_type_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :insurance_plans_ids

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :is_active

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :insurance_type_titles

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :insurance_company_titles

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :insurance_plan_titles

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :insurance_type_title

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :created_by

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :is_plan

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['id'] = 'id'
      @_hash['fiscal_year_id'] = 'fiscalYearId'
      @_hash['insurance_coverage_id'] = 'insuranceCoverageId'
      @_hash['coverage_rial'] = 'coverageRial'
      @_hash['coverage_euro'] = 'coverageEuro'
      @_hash['from_price'] = 'fromPrice'
      @_hash['to_price'] = 'toPrice'
      @_hash['is_discount'] = 'isDiscount'
      @_hash['coverage_value_type'] = 'coverageValueType'
      @_hash['coverage_string_value'] = 'coverageStringValue'
      @_hash['insurance_type_ids'] = 'insuranceTypeIds'
      @_hash['insurance_company_ids'] = 'insuranceCompanyIds'
      @_hash['selected'] = 'selected'
      @_hash['is_visible'] = 'isVisible'
      @_hash['insurance_type_id'] = 'insuranceTypeId'
      @_hash['insurance_plans_ids'] = 'insurancePlansIds'
      @_hash['is_active'] = 'isActive'
      @_hash['insurance_type_titles'] = 'insuranceTypeTitles'
      @_hash['insurance_company_titles'] = 'insuranceCompanyTitles'
      @_hash['insurance_plan_titles'] = 'insurancePlanTitles'
      @_hash['insurance_type_title'] = 'insuranceTypeTitle'
      @_hash['created_by'] = 'createdBy'
      @_hash['is_plan'] = 'isPlan'
      @_hash
    end

    def initialize(id = nil,
                   fiscal_year_id = nil,
                   insurance_coverage_id = nil,
                   coverage_rial = nil,
                   coverage_string_value = nil,
                   selected = nil,
                   coverage_euro = nil,
                   from_price = nil,
                   to_price = nil,
                   is_discount = nil,
                   coverage_value_type = nil,
                   insurance_type_ids = nil,
                   insurance_company_ids = nil,
                   is_visible = nil,
                   insurance_type_id = nil,
                   insurance_plans_ids = nil,
                   is_active = nil,
                   insurance_type_titles = nil,
                   insurance_company_titles = nil,
                   insurance_plan_titles = nil,
                   insurance_type_title = nil,
                   created_by = nil,
                   is_plan = nil)
      @id = id
      @fiscal_year_id = fiscal_year_id
      @insurance_coverage_id = insurance_coverage_id
      @coverage_rial = coverage_rial
      @coverage_euro = coverage_euro
      @from_price = from_price
      @to_price = to_price
      @is_discount = is_discount
      @coverage_value_type = coverage_value_type
      @coverage_string_value = coverage_string_value
      @insurance_type_ids = insurance_type_ids
      @insurance_company_ids = insurance_company_ids
      @selected = selected
      @is_visible = is_visible
      @insurance_type_id = insurance_type_id
      @insurance_plans_ids = insurance_plans_ids
      @is_active = is_active
      @insurance_type_titles = insurance_type_titles
      @insurance_company_titles = insurance_company_titles
      @insurance_plan_titles = insurance_plan_titles
      @insurance_type_title = insurance_type_title
      @created_by = created_by
      @is_plan = is_plan
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      id = hash['id']
      fiscal_year_id = hash['fiscalYearId']
      insurance_coverage_id = hash['insuranceCoverageId']
      coverage_rial = hash['coverageRial']
      coverage_string_value = hash['coverageStringValue']
      selected = hash['selected']
      coverage_euro = hash['coverageEuro']
      from_price = hash['fromPrice']
      to_price = hash['toPrice']
      is_discount = hash['isDiscount']
      coverage_value_type = hash['coverageValueType']
      insurance_type_ids = hash['insuranceTypeIds']
      insurance_company_ids = hash['insuranceCompanyIds']
      is_visible = hash['isVisible']
      insurance_type_id = hash['insuranceTypeId']
      insurance_plans_ids = hash['insurancePlansIds']
      is_active = hash['isActive']
      insurance_type_titles = hash['insuranceTypeTitles']
      insurance_company_titles = hash['insuranceCompanyTitles']
      insurance_plan_titles = hash['insurancePlanTitles']
      insurance_type_title = hash['insuranceTypeTitle']
      created_by = hash['createdBy']
      is_plan = hash['isPlan']

      # Create object from extracted values.
      EverySquareMeterCoverage.new(id,
                                   fiscal_year_id,
                                   insurance_coverage_id,
                                   coverage_rial,
                                   coverage_string_value,
                                   selected,
                                   coverage_euro,
                                   from_price,
                                   to_price,
                                   is_discount,
                                   coverage_value_type,
                                   insurance_type_ids,
                                   insurance_company_ids,
                                   is_visible,
                                   insurance_type_id,
                                   insurance_plans_ids,
                                   is_active,
                                   insurance_type_titles,
                                   insurance_company_titles,
                                   insurance_plan_titles,
                                   insurance_type_title,
                                   created_by,
                                   is_plan)
    end
  end
end
