# easy_bimeh_landing
#
# This file was automatically generated by APIMATIC
# v2.0 ( https://apimatic.io ).

module EasyBimehLanding
  # با توجه به API ممکن است تغییر کند
  class ExtraData < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :alias_name

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['alias_name'] = 'aliasName'
      @_hash
    end

    def initialize(alias_name = nil)
      @alias_name = alias_name
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      alias_name = hash['aliasName']

      # Create object from extracted values.
      ExtraData.new(alias_name)
    end
  end
end
