# easy_bimeh_landing
#
# This file was automatically generated by APIMATIC
# v2.0 ( https://apimatic.io ).

module EasyBimehLanding
  # ExtraDataBaseModelSpecialPlan Model.
  class ExtraDataBaseModelSpecialPlan < BaseModel
    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :insurance_types_count

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['insurance_types_count'] = 'insuranceTypesCount'
      @_hash
    end

    def initialize(insurance_types_count = nil)
      @insurance_types_count = insurance_types_count
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      insurance_types_count = hash['insuranceTypesCount']

      # Create object from extracted values.
      ExtraDataBaseModelSpecialPlan.new(insurance_types_count)
    end
  end
end
