# easy_bimeh_landing
#
# This file was automatically generated by APIMATIC
# v2.0 ( https://apimatic.io ).

module EasyBimehLanding
  # FireInsurancePolicyExtendView Model.
  class FireInsurancePolicyExtendView < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :building_type_param_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :skeleton_type_building_param_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :building_use_type_param_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :unit_count

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :every_square_meter_coverage_rate_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :city_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :province_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :building_area

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :value_of_appliances_furnishing

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :insurance_coverage_ids

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :only_appliances_furnishings

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :insurance_coverage_price

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :insurance_policy_commitment_ceiling

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :value_per_square_meter_rate

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :build_year

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :zip_code

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :address_place_building

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :risk_level_discount

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :base_premium

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :all_premium

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :insurance_company_discount_rate

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :insurance_company_discount

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :insurance_centre_discount

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :coupen_discount

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :all_discount

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :exchange_premium

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['building_type_param_id'] = 'buildingTypeParamId'
      @_hash['skeleton_type_building_param_id'] =
        'skeletonTypeBuildingParamId'
      @_hash['building_use_type_param_id'] = 'buildingUseTypeParamId'
      @_hash['unit_count'] = 'unitCount'
      @_hash['every_square_meter_coverage_rate_id'] =
        'everySquareMeterCoverageRateId'
      @_hash['city_id'] = 'cityId'
      @_hash['province_id'] = 'provinceId'
      @_hash['building_area'] = 'buildingArea'
      @_hash['value_of_appliances_furnishing'] = 'valueOfAppliancesFurnishing'
      @_hash['insurance_coverage_ids'] = '_InsuranceCoverageIds'
      @_hash['only_appliances_furnishings'] = 'onlyAppliancesFurnishings'
      @_hash['insurance_coverage_price'] = 'insuranceCoveragePrice'
      @_hash['insurance_policy_commitment_ceiling'] =
        'insurancePolicyCommitmentCeiling'
      @_hash['value_per_square_meter_rate'] = 'valuePerSquareMeterRate'
      @_hash['build_year'] = 'buildYear'
      @_hash['zip_code'] = 'zipCode'
      @_hash['address_place_building'] = 'addressPlaceBuilding'
      @_hash['risk_level_discount'] = 'riskLevelDiscount'
      @_hash['base_premium'] = 'basePremium'
      @_hash['all_premium'] = 'allPremium'
      @_hash['insurance_company_discount_rate'] =
        'insuranceCompanyDiscountRate'
      @_hash['insurance_company_discount'] = 'insuranceCompanyDiscount'
      @_hash['insurance_centre_discount'] = 'insuranceCentreDiscount'
      @_hash['coupen_discount'] = 'coupenDiscount'
      @_hash['all_discount'] = 'allDiscount'
      @_hash['exchange_premium'] = 'exchangePremium'
      @_hash
    end

    def initialize(every_square_meter_coverage_rate_id = nil,
                   only_appliances_furnishings = nil,
                   risk_level_discount = nil,
                   insurance_company_discount_rate = nil,
                   insurance_company_discount = nil,
                   insurance_centre_discount = nil,
                   coupen_discount = nil,
                   all_discount = nil,
                   exchange_premium = nil,
                   building_type_param_id = nil,
                   skeleton_type_building_param_id = nil,
                   building_use_type_param_id = nil,
                   unit_count = nil,
                   city_id = nil,
                   province_id = nil,
                   building_area = nil,
                   value_of_appliances_furnishing = nil,
                   insurance_coverage_ids = nil,
                   insurance_coverage_price = nil,
                   insurance_policy_commitment_ceiling = nil,
                   value_per_square_meter_rate = nil,
                   build_year = nil,
                   zip_code = nil,
                   address_place_building = nil,
                   base_premium = nil,
                   all_premium = nil)
      @building_type_param_id = building_type_param_id
      @skeleton_type_building_param_id = skeleton_type_building_param_id
      @building_use_type_param_id = building_use_type_param_id
      @unit_count = unit_count
      @every_square_meter_coverage_rate_id =
        every_square_meter_coverage_rate_id
      @city_id = city_id
      @province_id = province_id
      @building_area = building_area
      @value_of_appliances_furnishing = value_of_appliances_furnishing
      @insurance_coverage_ids = insurance_coverage_ids
      @only_appliances_furnishings = only_appliances_furnishings
      @insurance_coverage_price = insurance_coverage_price
      @insurance_policy_commitment_ceiling =
        insurance_policy_commitment_ceiling
      @value_per_square_meter_rate = value_per_square_meter_rate
      @build_year = build_year
      @zip_code = zip_code
      @address_place_building = address_place_building
      @risk_level_discount = risk_level_discount
      @base_premium = base_premium
      @all_premium = all_premium
      @insurance_company_discount_rate = insurance_company_discount_rate
      @insurance_company_discount = insurance_company_discount
      @insurance_centre_discount = insurance_centre_discount
      @coupen_discount = coupen_discount
      @all_discount = all_discount
      @exchange_premium = exchange_premium
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      every_square_meter_coverage_rate_id =
        hash['everySquareMeterCoverageRateId']
      only_appliances_furnishings = hash['onlyAppliancesFurnishings']
      risk_level_discount = hash['riskLevelDiscount']
      insurance_company_discount_rate = hash['insuranceCompanyDiscountRate']
      insurance_company_discount = hash['insuranceCompanyDiscount']
      insurance_centre_discount = hash['insuranceCentreDiscount']
      coupen_discount = hash['coupenDiscount']
      all_discount = hash['allDiscount']
      exchange_premium = hash['exchangePremium']
      building_type_param_id = hash['buildingTypeParamId']
      skeleton_type_building_param_id = hash['skeletonTypeBuildingParamId']
      building_use_type_param_id = hash['buildingUseTypeParamId']
      unit_count = hash['unitCount']
      city_id = hash['cityId']
      province_id = hash['provinceId']
      building_area = hash['buildingArea']
      value_of_appliances_furnishing = hash['valueOfAppliancesFurnishing']
      insurance_coverage_ids = hash['_InsuranceCoverageIds']
      insurance_coverage_price = hash['insuranceCoveragePrice']
      insurance_policy_commitment_ceiling =
        hash['insurancePolicyCommitmentCeiling']
      value_per_square_meter_rate = hash['valuePerSquareMeterRate']
      build_year = hash['buildYear']
      zip_code = hash['zipCode']
      address_place_building = hash['addressPlaceBuilding']
      base_premium = hash['basePremium']
      all_premium = hash['allPremium']

      # Create object from extracted values.
      FireInsurancePolicyExtendView.new(every_square_meter_coverage_rate_id,
                                        only_appliances_furnishings,
                                        risk_level_discount,
                                        insurance_company_discount_rate,
                                        insurance_company_discount,
                                        insurance_centre_discount,
                                        coupen_discount,
                                        all_discount,
                                        exchange_premium,
                                        building_type_param_id,
                                        skeleton_type_building_param_id,
                                        building_use_type_param_id,
                                        unit_count,
                                        city_id,
                                        province_id,
                                        building_area,
                                        value_of_appliances_furnishing,
                                        insurance_coverage_ids,
                                        insurance_coverage_price,
                                        insurance_policy_commitment_ceiling,
                                        value_per_square_meter_rate,
                                        build_year,
                                        zip_code,
                                        address_place_building,
                                        base_premium,
                                        all_premium)
    end
  end
end
