# easy_bimeh_landing
#
# This file was automatically generated by APIMATIC
# v2.0 ( https://apimatic.io ).

module EasyBimehLanding
  # GalleryDetail Model.
  class GalleryDetail < BaseModel
    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :gallery_id

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :meta_media_file_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :meta_media_file_url

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['gallery_id'] = 'galleryId'
      @_hash['meta_media_file_id'] = 'metaMediaFileId'
      @_hash['meta_media_file_url'] = 'metaMediaFileUrl'
      @_hash
    end

    def initialize(gallery_id = nil,
                   meta_media_file_id = nil,
                   meta_media_file_url = nil)
      @gallery_id = gallery_id
      @meta_media_file_id = meta_media_file_id
      @meta_media_file_url = meta_media_file_url
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      gallery_id = hash['galleryId']
      meta_media_file_id = hash['metaMediaFileId']
      meta_media_file_url = hash['metaMediaFileUrl']

      # Create object from extracted values.
      GalleryDetail.new(gallery_id,
                        meta_media_file_id,
                        meta_media_file_url)
    end
  end
end
