# easy_bimeh_landing
#
# This file was automatically generated by APIMATIC
# v2.0 ( https://apimatic.io ).

module EasyBimehLanding
  # InsuranceCentre Model.
  class InsuranceCentre < BaseModel
    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :person_id

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :personality_type

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :insurance_centre_type

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :register_status

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :center_name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :center_code

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :branch_count

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :registration_number

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :free_use_golden_pack_expire_date

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :city_id

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :cash_payment

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :show_in_easy_bimeh

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :installments_payment

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :is_initial_applicant

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :branchs_count

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :employees_count

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :zone_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :sms_charging_stock

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :independent_branch

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :disable_reason

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :terms_conditions

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :disable_reason_description

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :unlimited_account

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :white_label

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :phone

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :fax

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :address

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :zip_code

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :email

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :payment_url

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :callback_url

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :callback_url_whitelabel

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :web_site

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :latitude

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :longitude

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :is_active

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :insurance_centre_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :city_region_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :province_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :city_name

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :meta_media_activity_licence_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :meta_media_activity_licence_url

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :create_on_persian_date

    # TODO: Write general description for this method
    # @return [List of Integer]
    attr_accessor :insurance_company_id

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :active_package_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :package_activation_last_date

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :license_api_key

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :verify_request_url

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :online_payment

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :card_to_card_payment

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :bank_transfer_payment

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :cash_on_delivery

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :bank_transfer_same_online_payment_info

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :bank_param_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :account_owner

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :account_number

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :iban

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :card_bank_param_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :card_account_owner

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :card_account_number

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :bank_transfer_param_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :bank_transfer_account_owner

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :bank_transfer_account_number

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :bank_transfer_iban

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['id'] = 'id'
      @_hash['person_id'] = 'personId'
      @_hash['personality_type'] = 'personalityType'
      @_hash['insurance_centre_type'] = 'insuranceCentreType'
      @_hash['register_status'] = 'registerStatus'
      @_hash['center_name'] = 'centerName'
      @_hash['center_code'] = 'centerCode'
      @_hash['branch_count'] = 'branchCount'
      @_hash['registration_number'] = 'registrationNumber'
      @_hash['free_use_golden_pack_expire_date'] =
        'freeUseGoldenPackExpireDate'
      @_hash['city_id'] = 'cityId'
      @_hash['cash_payment'] = 'cashPayment'
      @_hash['show_in_easy_bimeh'] = 'showInEasyBimeh'
      @_hash['installments_payment'] = 'installmentsPayment'
      @_hash['is_initial_applicant'] = 'isInitialApplicant'
      @_hash['branchs_count'] = 'branchsCount'
      @_hash['employees_count'] = 'employeesCount'
      @_hash['zone_id'] = 'zoneId'
      @_hash['sms_charging_stock'] = 'smsChargingStock'
      @_hash['independent_branch'] = 'independentBranch'
      @_hash['disable_reason'] = 'disableReason'
      @_hash['terms_conditions'] = 'termsConditions'
      @_hash['disable_reason_description'] = 'disableReasonDescription'
      @_hash['unlimited_account'] = 'unlimitedAccount'
      @_hash['white_label'] = 'whiteLabel'
      @_hash['phone'] = 'phone'
      @_hash['fax'] = 'fax'
      @_hash['address'] = 'address'
      @_hash['zip_code'] = 'zipCode'
      @_hash['email'] = 'email'
      @_hash['payment_url'] = 'paymentUrl'
      @_hash['callback_url'] = 'callbackUrl'
      @_hash['callback_url_whitelabel'] = 'callbackUrlWhitelabel'
      @_hash['web_site'] = 'webSite'
      @_hash['latitude'] = 'latitude'
      @_hash['longitude'] = 'longitude'
      @_hash['is_active'] = 'isActive'
      @_hash['insurance_centre_id'] = 'insuranceCentreId'
      @_hash['city_region_id'] = 'cityRegionId'
      @_hash['province_id'] = 'provinceId'
      @_hash['city_name'] = 'cityName'
      @_hash['meta_media_activity_licence_id'] = 'metaMediaActivityLicenceId'
      @_hash['meta_media_activity_licence_url'] =
        'metaMediaActivityLicenceUrl'
      @_hash['create_on_persian_date'] = 'createOnPersianDate'
      @_hash['insurance_company_id'] = 'insuranceCompanyId'
      @_hash['active_package_id'] = 'activePackageId'
      @_hash['package_activation_last_date'] = 'packageActivationLastDate'
      @_hash['license_api_key'] = 'licenseApiKey'
      @_hash['verify_request_url'] = 'verifyRequestUrl'
      @_hash['online_payment'] = 'onlinePayment'
      @_hash['card_to_card_payment'] = 'cardToCardPayment'
      @_hash['bank_transfer_payment'] = 'bankTransferPayment'
      @_hash['cash_on_delivery'] = 'cashOnDelivery'
      @_hash['bank_transfer_same_online_payment_info'] =
        'bankTransferSameOnlinePaymentInfo'
      @_hash['bank_param_id'] = 'bankParamId'
      @_hash['account_owner'] = 'accountOwner'
      @_hash['account_number'] = 'accountNumber'
      @_hash['iban'] = 'iban'
      @_hash['card_bank_param_id'] = 'cardBankParamId'
      @_hash['card_account_owner'] = 'cardAccountOwner'
      @_hash['card_account_number'] = 'cardAccountNumber'
      @_hash['bank_transfer_param_id'] = 'bankTransferParamId'
      @_hash['bank_transfer_account_owner'] = 'bankTransferAccountOwner'
      @_hash['bank_transfer_account_number'] = 'bankTransferAccountNumber'
      @_hash['bank_transfer_iban'] = 'bankTransferIBAN'
      @_hash
    end

    def initialize(id = nil,
                   person_id = nil,
                   personality_type = nil,
                   insurance_centre_type = nil,
                   register_status = nil,
                   center_name = nil,
                   center_code = nil,
                   registration_number = nil,
                   free_use_golden_pack_expire_date = nil,
                   city_id = nil,
                   cash_payment = nil,
                   show_in_easy_bimeh = nil,
                   installments_payment = nil,
                   is_initial_applicant = nil,
                   branchs_count = nil,
                   employees_count = nil,
                   white_label = nil,
                   phone = nil,
                   fax = nil,
                   address = nil,
                   zip_code = nil,
                   email = nil,
                   web_site = nil,
                   latitude = nil,
                   longitude = nil,
                   is_active = nil,
                   meta_media_activity_licence_id = nil,
                   create_on_persian_date = nil,
                   insurance_company_id = nil,
                   active_package_id = nil,
                   package_activation_last_date = nil,
                   online_payment = nil,
                   card_to_card_payment = nil,
                   bank_transfer_payment = nil,
                   cash_on_delivery = nil,
                   bank_transfer_same_online_payment_info = nil,
                   bank_param_id = nil,
                   account_owner = nil,
                   account_number = nil,
                   iban = nil,
                   card_bank_param_id = nil,
                   card_account_owner = nil,
                   card_account_number = nil,
                   bank_transfer_param_id = nil,
                   bank_transfer_account_owner = nil,
                   bank_transfer_account_number = nil,
                   bank_transfer_iban = nil,
                   branch_count = nil,
                   zone_id = nil,
                   sms_charging_stock = nil,
                   independent_branch = nil,
                   disable_reason = nil,
                   terms_conditions = nil,
                   disable_reason_description = nil,
                   unlimited_account = nil,
                   payment_url = nil,
                   callback_url = nil,
                   callback_url_whitelabel = nil,
                   insurance_centre_id = nil,
                   city_region_id = nil,
                   province_id = nil,
                   city_name = nil,
                   meta_media_activity_licence_url = nil,
                   license_api_key = nil,
                   verify_request_url = nil)
      @id = id
      @person_id = person_id
      @personality_type = personality_type
      @insurance_centre_type = insurance_centre_type
      @register_status = register_status
      @center_name = center_name
      @center_code = center_code
      @branch_count = branch_count
      @registration_number = registration_number
      @free_use_golden_pack_expire_date = free_use_golden_pack_expire_date
      @city_id = city_id
      @cash_payment = cash_payment
      @show_in_easy_bimeh = show_in_easy_bimeh
      @installments_payment = installments_payment
      @is_initial_applicant = is_initial_applicant
      @branchs_count = branchs_count
      @employees_count = employees_count
      @zone_id = zone_id
      @sms_charging_stock = sms_charging_stock
      @independent_branch = independent_branch
      @disable_reason = disable_reason
      @terms_conditions = terms_conditions
      @disable_reason_description = disable_reason_description
      @unlimited_account = unlimited_account
      @white_label = white_label
      @phone = phone
      @fax = fax
      @address = address
      @zip_code = zip_code
      @email = email
      @payment_url = payment_url
      @callback_url = callback_url
      @callback_url_whitelabel = callback_url_whitelabel
      @web_site = web_site
      @latitude = latitude
      @longitude = longitude
      @is_active = is_active
      @insurance_centre_id = insurance_centre_id
      @city_region_id = city_region_id
      @province_id = province_id
      @city_name = city_name
      @meta_media_activity_licence_id = meta_media_activity_licence_id
      @meta_media_activity_licence_url = meta_media_activity_licence_url
      @create_on_persian_date = create_on_persian_date
      @insurance_company_id = insurance_company_id
      @active_package_id = active_package_id
      @package_activation_last_date = package_activation_last_date
      @license_api_key = license_api_key
      @verify_request_url = verify_request_url
      @online_payment = online_payment
      @card_to_card_payment = card_to_card_payment
      @bank_transfer_payment = bank_transfer_payment
      @cash_on_delivery = cash_on_delivery
      @bank_transfer_same_online_payment_info =
        bank_transfer_same_online_payment_info
      @bank_param_id = bank_param_id
      @account_owner = account_owner
      @account_number = account_number
      @iban = iban
      @card_bank_param_id = card_bank_param_id
      @card_account_owner = card_account_owner
      @card_account_number = card_account_number
      @bank_transfer_param_id = bank_transfer_param_id
      @bank_transfer_account_owner = bank_transfer_account_owner
      @bank_transfer_account_number = bank_transfer_account_number
      @bank_transfer_iban = bank_transfer_iban
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      id = hash['id']
      person_id = hash['personId']
      personality_type = hash['personalityType']
      insurance_centre_type = hash['insuranceCentreType']
      register_status = hash['registerStatus']
      center_name = hash['centerName']
      center_code = hash['centerCode']
      registration_number = hash['registrationNumber']
      free_use_golden_pack_expire_date = hash['freeUseGoldenPackExpireDate']
      city_id = hash['cityId']
      cash_payment = hash['cashPayment']
      show_in_easy_bimeh = hash['showInEasyBimeh']
      installments_payment = hash['installmentsPayment']
      is_initial_applicant = hash['isInitialApplicant']
      branchs_count = hash['branchsCount']
      employees_count = hash['employeesCount']
      white_label = hash['whiteLabel']
      phone = hash['phone']
      fax = hash['fax']
      address = hash['address']
      zip_code = hash['zipCode']
      email = hash['email']
      web_site = hash['webSite']
      latitude = hash['latitude']
      longitude = hash['longitude']
      is_active = hash['isActive']
      meta_media_activity_licence_id = hash['metaMediaActivityLicenceId']
      create_on_persian_date = hash['createOnPersianDate']
      insurance_company_id = hash['insuranceCompanyId']
      active_package_id = hash['activePackageId']
      package_activation_last_date = hash['packageActivationLastDate']
      online_payment = hash['onlinePayment']
      card_to_card_payment = hash['cardToCardPayment']
      bank_transfer_payment = hash['bankTransferPayment']
      cash_on_delivery = hash['cashOnDelivery']
      bank_transfer_same_online_payment_info =
        hash['bankTransferSameOnlinePaymentInfo']
      bank_param_id = hash['bankParamId']
      account_owner = hash['accountOwner']
      account_number = hash['accountNumber']
      iban = hash['iban']
      card_bank_param_id = hash['cardBankParamId']
      card_account_owner = hash['cardAccountOwner']
      card_account_number = hash['cardAccountNumber']
      bank_transfer_param_id = hash['bankTransferParamId']
      bank_transfer_account_owner = hash['bankTransferAccountOwner']
      bank_transfer_account_number = hash['bankTransferAccountNumber']
      bank_transfer_iban = hash['bankTransferIBAN']
      branch_count = hash['branchCount']
      zone_id = hash['zoneId']
      sms_charging_stock = hash['smsChargingStock']
      independent_branch = hash['independentBranch']
      disable_reason = hash['disableReason']
      terms_conditions = hash['termsConditions']
      disable_reason_description = hash['disableReasonDescription']
      unlimited_account = hash['unlimitedAccount']
      payment_url = hash['paymentUrl']
      callback_url = hash['callbackUrl']
      callback_url_whitelabel = hash['callbackUrlWhitelabel']
      insurance_centre_id = hash['insuranceCentreId']
      city_region_id = hash['cityRegionId']
      province_id = hash['provinceId']
      city_name = hash['cityName']
      meta_media_activity_licence_url = hash['metaMediaActivityLicenceUrl']
      license_api_key = hash['licenseApiKey']
      verify_request_url = hash['verifyRequestUrl']

      # Create object from extracted values.
      InsuranceCentre.new(id,
                          person_id,
                          personality_type,
                          insurance_centre_type,
                          register_status,
                          center_name,
                          center_code,
                          registration_number,
                          free_use_golden_pack_expire_date,
                          city_id,
                          cash_payment,
                          show_in_easy_bimeh,
                          installments_payment,
                          is_initial_applicant,
                          branchs_count,
                          employees_count,
                          white_label,
                          phone,
                          fax,
                          address,
                          zip_code,
                          email,
                          web_site,
                          latitude,
                          longitude,
                          is_active,
                          meta_media_activity_licence_id,
                          create_on_persian_date,
                          insurance_company_id,
                          active_package_id,
                          package_activation_last_date,
                          online_payment,
                          card_to_card_payment,
                          bank_transfer_payment,
                          cash_on_delivery,
                          bank_transfer_same_online_payment_info,
                          bank_param_id,
                          account_owner,
                          account_number,
                          iban,
                          card_bank_param_id,
                          card_account_owner,
                          card_account_number,
                          bank_transfer_param_id,
                          bank_transfer_account_owner,
                          bank_transfer_account_number,
                          bank_transfer_iban,
                          branch_count,
                          zone_id,
                          sms_charging_stock,
                          independent_branch,
                          disable_reason,
                          terms_conditions,
                          disable_reason_description,
                          unlimited_account,
                          payment_url,
                          callback_url,
                          callback_url_whitelabel,
                          insurance_centre_id,
                          city_region_id,
                          province_id,
                          city_name,
                          meta_media_activity_licence_url,
                          license_api_key,
                          verify_request_url)
    end
  end
end
