# easy_bimeh_landing
#
# This file was automatically generated by APIMATIC
# v2.0 ( https://apimatic.io ).

module EasyBimehLanding
  # LiabilityDoctorInsurancePolicyExtendView Model.
  class LiabilityDoctorInsurancePolicyExtendView < BaseModel
    # شناسه ی نرخ پوشش پزشکی
    # @return [String]
    attr_accessor :liability_doctor_coverage_rate_id

    # شناسه ی دوره های فعالیت
    # @return [String]
    attr_accessor :activity_area_param_id

    # شاسه ی تخصص
    # @return [String]
    attr_accessor :expertise_param_id

    # شناسه ی سقف تعهد
    # @return [String]
    attr_accessor :commitment_ceiling_param_id

    # شناسه ی تخفیف
    # @return [String]
    attr_accessor :insurance_risk_level_id

    # تاریخ پایان بیمه نامه
    # @return [String]
    attr_accessor :current_insurance_deadline

    # نرخ تخفیف پوشش
    # @return [String]
    attr_accessor :risk_level_discount_rate

    # خسارت جانی
    # @return [String]
    attr_accessor :physical_commitment

    # نرخ تخفیف
    # @return [String]
    attr_accessor :discount_rate

    # پوشش پایه
    # @return [String]
    attr_accessor :base_premium

    # پوشش ها
    # @return [String]
    attr_accessor :all_premium

    # اطلاعات اضافه
    # @return [String]
    attr_accessor :all_extra_values

    # نرخ تخفیف شرکت بیمه
    # @return [Integer]
    attr_accessor :insurance_company_discount_rate

    # لیست تخفیفات
    # @return [Integer]
    attr_accessor :all_discount

    # نوع ارز حق بیمه
    # @return [Integer]
    attr_accessor :exchange_premium

    # نام پزشک
    # @return [String]
    attr_accessor :doctor_name

    # شماره ی نظام پزشکی
    # @return [String]
    attr_accessor :medical_system_no

    # آدرس
    # @return [String]
    attr_accessor :address

    # آیا رزیدنت است؟
    # @return [Boolean]
    attr_accessor :is_resident

    # آیا دانشجو است؟
    # @return [Boolean]
    attr_accessor :is_student

    # دارای مطب؟
    # @return [String]
    attr_accessor :has_clinic

    # شناسه ی گواهی نظام پزشکی
    # @return [String]
    attr_accessor :meta_media_medical_system_license_id

    # آدرس گواهی نظام پزشکی
    # @return [String]
    attr_accessor :meta_media_medical_system_license_url

    # شناسه ی کارت ملی
    # @return [String]
    attr_accessor :meta_media_national_card_id

    # آدرس کارت ملی
    # @return [String]
    attr_accessor :meta_media_national_card_url

    # شناسه ی بیمه نامه ی کنونی
    # @return [String]
    attr_accessor :meta_media_current_insurance_policy_id

    # آدرس بیمه نامه ی کنونی
    # @return [String]
    attr_accessor :meta_media_current_insurance_policy_url

    # شناسه ی دوره های بیمه نامه
    # @return [String]
    attr_accessor :activity_area_enum_name

    # نام دوره ی بیمه نامه
    # @return [String]
    attr_accessor :activity_area_title

    # نام تخصص
    # @return [String]
    attr_accessor :expertise_title

    # وضعیت پزشک
    # @return [String]
    attr_accessor :docter_status_title

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['liability_doctor_coverage_rate_id'] =
        'liabilityDoctorCoverageRateId'
      @_hash['activity_area_param_id'] = 'activityAreaParamId'
      @_hash['expertise_param_id'] = 'expertiseParamId'
      @_hash['commitment_ceiling_param_id'] = 'commitmentCeilingParamId'
      @_hash['insurance_risk_level_id'] = 'insuranceRiskLevelId'
      @_hash['current_insurance_deadline'] = 'currentInsuranceDeadline'
      @_hash['risk_level_discount_rate'] = 'riskLevelDiscountRate'
      @_hash['physical_commitment'] = 'physicalCommitment'
      @_hash['discount_rate'] = 'discountRate'
      @_hash['base_premium'] = 'basePremium'
      @_hash['all_premium'] = 'allPremium'
      @_hash['all_extra_values'] = 'allExtraValues'
      @_hash['insurance_company_discount_rate'] =
        'insuranceCompanyDiscountRate'
      @_hash['all_discount'] = 'allDiscount'
      @_hash['exchange_premium'] = 'exchangePremium'
      @_hash['doctor_name'] = 'doctorName'
      @_hash['medical_system_no'] = 'medicalSystemNO'
      @_hash['address'] = 'address'
      @_hash['is_resident'] = 'isResident'
      @_hash['is_student'] = 'isStudent'
      @_hash['has_clinic'] = 'hasClinic'
      @_hash['meta_media_medical_system_license_id'] =
        'metaMediaMedicalSystemLicenseId'
      @_hash['meta_media_medical_system_license_url'] =
        'metaMediaMedicalSystemLicenseUrl'
      @_hash['meta_media_national_card_id'] = 'metaMediaNationalCardId'
      @_hash['meta_media_national_card_url'] = 'metaMediaNationalCardUrl'
      @_hash['meta_media_current_insurance_policy_id'] =
        'metaMediaCurrentInsurancePolicyId'
      @_hash['meta_media_current_insurance_policy_url'] =
        'metaMediaCurrentInsurancePolicyUrl'
      @_hash['activity_area_enum_name'] = 'activityAreaEnumName'
      @_hash['activity_area_title'] = 'activityAreaTitle'
      @_hash['expertise_title'] = 'expertiseTitle'
      @_hash['docter_status_title'] = 'docterStatusTitle'
      @_hash
    end

    def initialize(insurance_company_discount_rate = nil,
                   all_discount = nil,
                   exchange_premium = nil,
                   is_resident = nil,
                   is_student = nil,
                   liability_doctor_coverage_rate_id = nil,
                   activity_area_param_id = nil,
                   expertise_param_id = nil,
                   commitment_ceiling_param_id = nil,
                   insurance_risk_level_id = nil,
                   current_insurance_deadline = nil,
                   risk_level_discount_rate = nil,
                   physical_commitment = nil,
                   discount_rate = nil,
                   base_premium = nil,
                   all_premium = nil,
                   all_extra_values = nil,
                   doctor_name = nil,
                   medical_system_no = nil,
                   address = nil,
                   has_clinic = nil,
                   meta_media_medical_system_license_id = nil,
                   meta_media_medical_system_license_url = nil,
                   meta_media_national_card_id = nil,
                   meta_media_national_card_url = nil,
                   meta_media_current_insurance_policy_id = nil,
                   meta_media_current_insurance_policy_url = nil,
                   activity_area_enum_name = nil,
                   activity_area_title = nil,
                   expertise_title = nil,
                   docter_status_title = nil)
      @liability_doctor_coverage_rate_id = liability_doctor_coverage_rate_id
      @activity_area_param_id = activity_area_param_id
      @expertise_param_id = expertise_param_id
      @commitment_ceiling_param_id = commitment_ceiling_param_id
      @insurance_risk_level_id = insurance_risk_level_id
      @current_insurance_deadline = current_insurance_deadline
      @risk_level_discount_rate = risk_level_discount_rate
      @physical_commitment = physical_commitment
      @discount_rate = discount_rate
      @base_premium = base_premium
      @all_premium = all_premium
      @all_extra_values = all_extra_values
      @insurance_company_discount_rate = insurance_company_discount_rate
      @all_discount = all_discount
      @exchange_premium = exchange_premium
      @doctor_name = doctor_name
      @medical_system_no = medical_system_no
      @address = address
      @is_resident = is_resident
      @is_student = is_student
      @has_clinic = has_clinic
      @meta_media_medical_system_license_id =
        meta_media_medical_system_license_id
      @meta_media_medical_system_license_url =
        meta_media_medical_system_license_url
      @meta_media_national_card_id = meta_media_national_card_id
      @meta_media_national_card_url = meta_media_national_card_url
      @meta_media_current_insurance_policy_id =
        meta_media_current_insurance_policy_id
      @meta_media_current_insurance_policy_url =
        meta_media_current_insurance_policy_url
      @activity_area_enum_name = activity_area_enum_name
      @activity_area_title = activity_area_title
      @expertise_title = expertise_title
      @docter_status_title = docter_status_title
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      insurance_company_discount_rate = hash['insuranceCompanyDiscountRate']
      all_discount = hash['allDiscount']
      exchange_premium = hash['exchangePremium']
      is_resident = hash['isResident']
      is_student = hash['isStudent']
      liability_doctor_coverage_rate_id = hash['liabilityDoctorCoverageRateId']
      activity_area_param_id = hash['activityAreaParamId']
      expertise_param_id = hash['expertiseParamId']
      commitment_ceiling_param_id = hash['commitmentCeilingParamId']
      insurance_risk_level_id = hash['insuranceRiskLevelId']
      current_insurance_deadline = hash['currentInsuranceDeadline']
      risk_level_discount_rate = hash['riskLevelDiscountRate']
      physical_commitment = hash['physicalCommitment']
      discount_rate = hash['discountRate']
      base_premium = hash['basePremium']
      all_premium = hash['allPremium']
      all_extra_values = hash['allExtraValues']
      doctor_name = hash['doctorName']
      medical_system_no = hash['medicalSystemNO']
      address = hash['address']
      has_clinic = hash['hasClinic']
      meta_media_medical_system_license_id =
        hash['metaMediaMedicalSystemLicenseId']
      meta_media_medical_system_license_url =
        hash['metaMediaMedicalSystemLicenseUrl']
      meta_media_national_card_id = hash['metaMediaNationalCardId']
      meta_media_national_card_url = hash['metaMediaNationalCardUrl']
      meta_media_current_insurance_policy_id =
        hash['metaMediaCurrentInsurancePolicyId']
      meta_media_current_insurance_policy_url =
        hash['metaMediaCurrentInsurancePolicyUrl']
      activity_area_enum_name = hash['activityAreaEnumName']
      activity_area_title = hash['activityAreaTitle']
      expertise_title = hash['expertiseTitle']
      docter_status_title = hash['docterStatusTitle']

      # Create object from extracted values.
      LiabilityDoctorInsurancePolicyExtendView.new(insurance_company_discount_rate,
                                                   all_discount,
                                                   exchange_premium,
                                                   is_resident,
                                                   is_student,
                                                   liability_doctor_coverage_rate_id,
                                                   activity_area_param_id,
                                                   expertise_param_id,
                                                   commitment_ceiling_param_id,
                                                   insurance_risk_level_id,
                                                   current_insurance_deadline,
                                                   risk_level_discount_rate,
                                                   physical_commitment,
                                                   discount_rate,
                                                   base_premium,
                                                   all_premium,
                                                   all_extra_values,
                                                   doctor_name,
                                                   medical_system_no,
                                                   address,
                                                   has_clinic,
                                                   meta_media_medical_system_license_id,
                                                   meta_media_medical_system_license_url,
                                                   meta_media_national_card_id,
                                                   meta_media_national_card_url,
                                                   meta_media_current_insurance_policy_id,
                                                   meta_media_current_insurance_policy_url,
                                                   activity_area_enum_name,
                                                   activity_area_title,
                                                   expertise_title,
                                                   docter_status_title)
    end
  end
end
