# easy_bimeh_landing
#
# This file was automatically generated by APIMATIC
# v2.0 ( https://apimatic.io ).

module EasyBimehLanding
  # SpecialPlan Model.
  class SpecialPlan < BaseModel
    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :key

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :count

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :title

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :policy_type

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :display

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :icon_position

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['key'] = 'key'
      @_hash['count'] = 'count'
      @_hash['title'] = 'title'
      @_hash['policy_type'] = 'policyType'
      @_hash['display'] = 'display'
      @_hash['icon_position'] = 'iconPosition'
      @_hash
    end

    def initialize(key = nil,
                   count = nil,
                   title = nil,
                   policy_type = nil,
                   icon_position = nil,
                   display = nil)
      @key = key
      @count = count
      @title = title
      @policy_type = policy_type
      @display = display
      @icon_position = icon_position
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      key = hash['key']
      count = hash['count']
      title = hash['title']
      policy_type = hash['policyType']
      icon_position = hash['iconPosition']
      display = hash['display']

      # Create object from extracted values.
      SpecialPlan.new(key,
                      count,
                      title,
                      policy_type,
                      icon_position,
                      display)
    end
  end
end
