# easy_bimeh_landing
#
# This file was automatically generated by APIMATIC
# v2.0 ( https://apimatic.io ).

module EasyBimehLanding
  # SummaryCard Model.
  class SummaryCard < BaseModel
    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :id

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :insurance_centre_id

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :article_type

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :title

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :summary

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :article_group

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :meta_media_file_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :meta_media_file_url

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :publish_persian_date

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['id'] = 'id'
      @_hash['insurance_centre_id'] = 'insuranceCentreId'
      @_hash['article_type'] = 'articleType'
      @_hash['title'] = 'title'
      @_hash['summary'] = 'summary'
      @_hash['article_group'] = 'articleGroup'
      @_hash['meta_media_file_id'] = 'metaMediaFileId'
      @_hash['meta_media_file_url'] = 'metaMediaFileUrl'
      @_hash['publish_persian_date'] = 'publishPersianDate'
      @_hash
    end

    def initialize(id = nil,
                   insurance_centre_id = nil,
                   article_type = nil,
                   title = nil,
                   summary = nil,
                   article_group = nil,
                   meta_media_file_id = nil,
                   meta_media_file_url = nil,
                   publish_persian_date = nil)
      @id = id
      @insurance_centre_id = insurance_centre_id
      @article_type = article_type
      @title = title
      @summary = summary
      @article_group = article_group
      @meta_media_file_id = meta_media_file_id
      @meta_media_file_url = meta_media_file_url
      @publish_persian_date = publish_persian_date
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      id = hash['id']
      insurance_centre_id = hash['insuranceCentreId']
      article_type = hash['articleType']
      title = hash['title']
      summary = hash['summary']
      article_group = hash['articleGroup']
      meta_media_file_id = hash['metaMediaFileId']
      meta_media_file_url = hash['metaMediaFileUrl']
      publish_persian_date = hash['publishPersianDate']

      # Create object from extracted values.
      SummaryCard.new(id,
                      insurance_centre_id,
                      article_type,
                      title,
                      summary,
                      article_group,
                      meta_media_file_id,
                      meta_media_file_url,
                      publish_persian_date)
    end
  end
end
