# easy_bimeh_landing
#
# This file was automatically generated by APIMATIC
# v2.0 ( https://apimatic.io ).

module EasyBimehLanding
  # TargetSite Model.
  class TargetSite < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :assembly_name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :class_name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :signature

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :signature2

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :member_type

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :generic_arguments

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['name'] = 'Name'
      @_hash['assembly_name'] = 'AssemblyName'
      @_hash['class_name'] = 'ClassName'
      @_hash['signature'] = 'Signature'
      @_hash['signature2'] = 'Signature2'
      @_hash['member_type'] = 'MemberType'
      @_hash['generic_arguments'] = 'GenericArguments'
      @_hash
    end

    def initialize(name = nil,
                   assembly_name = nil,
                   class_name = nil,
                   signature = nil,
                   signature2 = nil,
                   member_type = nil,
                   generic_arguments = nil)
      @name = name
      @assembly_name = assembly_name
      @class_name = class_name
      @signature = signature
      @signature2 = signature2
      @member_type = member_type
      @generic_arguments = generic_arguments
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      name = hash['Name']
      assembly_name = hash['AssemblyName']
      class_name = hash['ClassName']
      signature = hash['Signature']
      signature2 = hash['Signature2']
      member_type = hash['MemberType']
      generic_arguments = hash['GenericArguments']

      # Create object from extracted values.
      TargetSite.new(name,
                     assembly_name,
                     class_name,
                     signature,
                     signature2,
                     member_type,
                     generic_arguments)
    end
  end
end
