# easy_bimeh_landing
#
# This file was automatically generated by APIMATIC
# v2.0 ( https://apimatic.io ).

module EasyBimehLanding
  # TrackingDamageStatus Model.
  class TrackingDamageStatus < BaseModel
    # TODO: Write general description for this method
    # @return [List of TrackingDamageFile]
    attr_accessor :tracking_damage_file

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['tracking_damage_file'] = 'trackingDamageFile'
      @_hash
    end

    def initialize(tracking_damage_file = nil)
      @tracking_damage_file = tracking_damage_file
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      tracking_damage_file = nil
      unless hash['trackingDamageFile'].nil?
        tracking_damage_file = []
        hash['trackingDamageFile'].each do |structure|
          tracking_damage_file << (TrackingDamageFile.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      TrackingDamageStatus.new(tracking_damage_file)
    end
  end
end
