# easy_bimeh_landing
#
# This file was automatically generated by APIMATIC
# v2.0 ( https://apimatic.io ).

module EasyBimehLanding
  # TrackingDamageFileTrackinCode Model.
  class TrackingDamageFileTrackinCode < BaseModel
    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :id

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :tracking_damage_status_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :file_name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :title

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :url

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['id'] = 'id'
      @_hash['tracking_damage_status_id'] = 'trackingDamageStatusId'
      @_hash['file_name'] = 'fileName'
      @_hash['title'] = 'title'
      @_hash['url'] = 'url'
      @_hash
    end

    def initialize(id = nil,
                   tracking_damage_status_id = nil,
                   file_name = nil,
                   title = nil,
                   url = nil)
      @id = id
      @tracking_damage_status_id = tracking_damage_status_id
      @file_name = file_name
      @title = title
      @url = url
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      id = hash['id']
      tracking_damage_status_id = hash['trackingDamageStatusId']
      file_name = hash['fileName']
      title = hash['title']
      url = hash['url']

      # Create object from extracted values.
      TrackingDamageFileTrackinCode.new(id,
                                        tracking_damage_status_id,
                                        file_name,
                                        title,
                                        url)
    end
  end
end
