# easy_bimeh_landing
#
# This file was automatically generated by APIMATIC
# v2.0 ( https://apimatic.io ).

module EasyBimehLanding
  # TrackingCode Model.
  class TrackingCode < BaseModel
    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :id

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :insurance_type_id

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :insurance_centre_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :insurance_centre_name

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :insurance_company_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :insurance_company_title

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :insurance_policy_number

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :personality_type

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :damage_type

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :national_code

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :mobile

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :insured_profile

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :refrenced_user

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :reference_count

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :tracking_code

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :payment_type

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :payment_date

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :payment_persian_date

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :sub_domain

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :insurance_type_title

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :create_on

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :update_on

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :create_on_persian_date

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :update_on_persian_date

    # TODO: Write general description for this method
    # @return [List of TrackingDamageStatusTrackingCode]
    attr_accessor :tracking_damage_status

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['id'] = 'id'
      @_hash['insurance_type_id'] = 'insuranceTypeId'
      @_hash['insurance_centre_id'] = 'insuranceCentreId'
      @_hash['insurance_centre_name'] = 'insuranceCentreName'
      @_hash['insurance_company_id'] = 'insuranceCompanyId'
      @_hash['insurance_company_title'] = 'insuranceCompanyTitle'
      @_hash['insurance_policy_number'] = 'insurancePolicyNumber'
      @_hash['personality_type'] = 'personalityType'
      @_hash['damage_type'] = 'damageType'
      @_hash['name'] = 'name'
      @_hash['national_code'] = 'nationalCode'
      @_hash['mobile'] = 'mobile'
      @_hash['insured_profile'] = 'insuredProfile'
      @_hash['refrenced_user'] = 'refrencedUser'
      @_hash['reference_count'] = 'referenceCount'
      @_hash['tracking_code'] = 'trackingCode'
      @_hash['payment_type'] = 'paymentType'
      @_hash['payment_date'] = 'paymentDate'
      @_hash['payment_persian_date'] = 'paymentPersianDate'
      @_hash['sub_domain'] = 'subDomain'
      @_hash['insurance_type_title'] = 'insuranceTypeTitle'
      @_hash['create_on'] = 'createOn'
      @_hash['update_on'] = 'updateOn'
      @_hash['create_on_persian_date'] = 'createOnPersianDate'
      @_hash['update_on_persian_date'] = 'updateOnPersianDate'
      @_hash['tracking_damage_status'] = 'trackingDamageStatus'
      @_hash
    end

    def initialize(id = nil,
                   insurance_type_id = nil,
                   insurance_centre_id = nil,
                   insurance_centre_name = nil,
                   insurance_company_id = nil,
                   insurance_company_title = nil,
                   insurance_policy_number = nil,
                   personality_type = nil,
                   damage_type = nil,
                   name = nil,
                   national_code = nil,
                   mobile = nil,
                   insured_profile = nil,
                   tracking_code = nil,
                   payment_persian_date = nil,
                   sub_domain = nil,
                   create_on = nil,
                   create_on_persian_date = nil,
                   update_on_persian_date = nil,
                   tracking_damage_status = nil,
                   refrenced_user = nil,
                   reference_count = nil,
                   payment_type = nil,
                   payment_date = nil,
                   insurance_type_title = nil,
                   update_on = nil)
      @id = id
      @insurance_type_id = insurance_type_id
      @insurance_centre_id = insurance_centre_id
      @insurance_centre_name = insurance_centre_name
      @insurance_company_id = insurance_company_id
      @insurance_company_title = insurance_company_title
      @insurance_policy_number = insurance_policy_number
      @personality_type = personality_type
      @damage_type = damage_type
      @name = name
      @national_code = national_code
      @mobile = mobile
      @insured_profile = insured_profile
      @refrenced_user = refrenced_user
      @reference_count = reference_count
      @tracking_code = tracking_code
      @payment_type = payment_type
      @payment_date = payment_date
      @payment_persian_date = payment_persian_date
      @sub_domain = sub_domain
      @insurance_type_title = insurance_type_title
      @create_on = create_on
      @update_on = update_on
      @create_on_persian_date = create_on_persian_date
      @update_on_persian_date = update_on_persian_date
      @tracking_damage_status = tracking_damage_status
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      id = hash['id']
      insurance_type_id = hash['insuranceTypeId']
      insurance_centre_id = hash['insuranceCentreId']
      insurance_centre_name = hash['insuranceCentreName']
      insurance_company_id = hash['insuranceCompanyId']
      insurance_company_title = hash['insuranceCompanyTitle']
      insurance_policy_number = hash['insurancePolicyNumber']
      personality_type = hash['personalityType']
      damage_type = hash['damageType']
      name = hash['name']
      national_code = hash['nationalCode']
      mobile = hash['mobile']
      insured_profile = hash['insuredProfile']
      tracking_code = hash['trackingCode']
      payment_persian_date = hash['paymentPersianDate']
      sub_domain = hash['subDomain']
      create_on = hash['createOn']
      create_on_persian_date = hash['createOnPersianDate']
      update_on_persian_date = hash['updateOnPersianDate']
      # Parameter is an array, so we need to iterate through it
      tracking_damage_status = nil
      unless hash['trackingDamageStatus'].nil?
        tracking_damage_status = []
        hash['trackingDamageStatus'].each do |structure|
          tracking_damage_status << (TrackingDamageStatusTrackingCode.from_hash(structure) if structure)
        end
      end
      refrenced_user = hash['refrencedUser']
      reference_count = hash['referenceCount']
      payment_type = hash['paymentType']
      payment_date = hash['paymentDate']
      insurance_type_title = hash['insuranceTypeTitle']
      update_on = hash['updateOn']

      # Create object from extracted values.
      TrackingCode.new(id,
                       insurance_type_id,
                       insurance_centre_id,
                       insurance_centre_name,
                       insurance_company_id,
                       insurance_company_title,
                       insurance_policy_number,
                       personality_type,
                       damage_type,
                       name,
                       national_code,
                       mobile,
                       insured_profile,
                       tracking_code,
                       payment_persian_date,
                       sub_domain,
                       create_on,
                       create_on_persian_date,
                       update_on_persian_date,
                       tracking_damage_status,
                       refrenced_user,
                       reference_count,
                       payment_type,
                       payment_date,
                       insurance_type_title,
                       update_on)
    end
  end
end
