# easy_bimeh_landing
#
# This file was automatically generated by APIMATIC
# v2.0 ( https://apimatic.io ).

module EasyBimehLanding
  # TrackingDamageFile Model.
  class TrackingDamageFile < BaseModel
    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :url

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :title

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['id'] = 'id'
      @_hash['url'] = 'url'
      @_hash['title'] = 'title'
      @_hash
    end

    def initialize(id = nil,
                   url = nil,
                   title = nil)
      @id = id
      @url = url
      @title = title
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      id = hash['id']
      url = hash['url']
      title = hash['title']

      # Create object from extracted values.
      TrackingDamageFile.new(id,
                             url,
                             title)
    end
  end
end
