# easy_bimeh_landing
#
# This file was automatically generated by APIMATIC
# v2.0 ( https://apimatic.io ).

module EasyBimehLanding
  # TrackingDamageStatusTrackingCode Model.
  class TrackingDamageStatusTrackingCode < BaseModel
    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :id

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :tracking_damage_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :description

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :tracking_damage_status

    # TODO: Write general description for this method
    # @return [List of TrackingDamageFileTrackinCode]
    attr_accessor :tracking_damage_file

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['id'] = 'id'
      @_hash['tracking_damage_id'] = 'trackingDamageId'
      @_hash['description'] = 'description'
      @_hash['tracking_damage_status'] = 'trackingDamageStatus'
      @_hash['tracking_damage_file'] = 'trackingDamageFile'
      @_hash
    end

    def initialize(id = nil,
                   tracking_damage_id = nil,
                   tracking_damage_status = nil,
                   tracking_damage_file = nil,
                   description = nil)
      @id = id
      @tracking_damage_id = tracking_damage_id
      @description = description
      @tracking_damage_status = tracking_damage_status
      @tracking_damage_file = tracking_damage_file
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      id = hash['id']
      tracking_damage_id = hash['trackingDamageId']
      tracking_damage_status = hash['trackingDamageStatus']
      # Parameter is an array, so we need to iterate through it
      tracking_damage_file = nil
      unless hash['trackingDamageFile'].nil?
        tracking_damage_file = []
        hash['trackingDamageFile'].each do |structure|
          tracking_damage_file << (TrackingDamageFileTrackinCode.from_hash(structure) if structure)
        end
      end
      description = hash['description']

      # Create object from extracted values.
      TrackingDamageStatusTrackingCode.new(id,
                                           tracking_damage_id,
                                           tracking_damage_status,
                                           tracking_damage_file,
                                           description)
    end
  end
end
