# easy_bimeh_landing
#
# This file was automatically generated by APIMATIC
# v2.0 ( https://apimatic.io ).

module EasyBimehLanding
  # TravelInsurancePolicyFilter Model.
  class TravelInsurancePolicyFilter < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :zone_ids

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :travel_rate_plan_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :travel_insurance_policy_extend_ages

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :travel_duration_param

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :birth_date_persian

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :insurance_extra_coverage_ids

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :policy_term_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :insurance_centre_sub_domain_name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :insurance_centre_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :insurance_company_id

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :is_search_query

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :gift_code

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :customer_user_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['zone_ids'] = 'zoneIds'
      @_hash['travel_rate_plan_id'] = 'travelRatePlanId'
      @_hash['travel_insurance_policy_extend_ages'] =
        'travelInsurancePolicyExtendAges'
      @_hash['travel_duration_param'] = 'travelDurationParam'
      @_hash['birth_date_persian'] = 'birthDatePersian'
      @_hash['insurance_extra_coverage_ids'] = 'insuranceExtraCoverageIds'
      @_hash['policy_term_id'] = 'policyTermId'
      @_hash['insurance_centre_sub_domain_name'] =
        'insuranceCentreSubDomainName'
      @_hash['insurance_centre_id'] = 'insuranceCentreId'
      @_hash['insurance_company_id'] = 'insuranceCompanyId'
      @_hash['is_search_query'] = 'isSearchQuery'
      @_hash['gift_code'] = 'giftCode'
      @_hash['customer_user_id'] = 'customerUserId'
      @_hash
    end

    def initialize(is_search_query = nil,
                   zone_ids = nil,
                   travel_rate_plan_id = nil,
                   travel_insurance_policy_extend_ages = nil,
                   travel_duration_param = nil,
                   birth_date_persian = nil,
                   insurance_extra_coverage_ids = nil,
                   policy_term_id = nil,
                   insurance_centre_sub_domain_name = nil,
                   insurance_centre_id = nil,
                   insurance_company_id = nil,
                   gift_code = nil,
                   customer_user_id = nil)
      @zone_ids = zone_ids
      @travel_rate_plan_id = travel_rate_plan_id
      @travel_insurance_policy_extend_ages =
        travel_insurance_policy_extend_ages
      @travel_duration_param = travel_duration_param
      @birth_date_persian = birth_date_persian
      @insurance_extra_coverage_ids = insurance_extra_coverage_ids
      @policy_term_id = policy_term_id
      @insurance_centre_sub_domain_name = insurance_centre_sub_domain_name
      @insurance_centre_id = insurance_centre_id
      @insurance_company_id = insurance_company_id
      @is_search_query = is_search_query
      @gift_code = gift_code
      @customer_user_id = customer_user_id
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      is_search_query = hash['isSearchQuery']
      zone_ids = hash['zoneIds']
      travel_rate_plan_id = hash['travelRatePlanId']
      travel_insurance_policy_extend_ages =
        hash['travelInsurancePolicyExtendAges']
      travel_duration_param = hash['travelDurationParam']
      birth_date_persian = hash['birthDatePersian']
      insurance_extra_coverage_ids = hash['insuranceExtraCoverageIds']
      policy_term_id = hash['policyTermId']
      insurance_centre_sub_domain_name = hash['insuranceCentreSubDomainName']
      insurance_centre_id = hash['insuranceCentreId']
      insurance_company_id = hash['insuranceCompanyId']
      gift_code = hash['giftCode']
      customer_user_id = hash['customerUserId']

      # Create object from extracted values.
      TravelInsurancePolicyFilter.new(is_search_query,
                                      zone_ids,
                                      travel_rate_plan_id,
                                      travel_insurance_policy_extend_ages,
                                      travel_duration_param,
                                      birth_date_persian,
                                      insurance_extra_coverage_ids,
                                      policy_term_id,
                                      insurance_centre_sub_domain_name,
                                      insurance_centre_id,
                                      insurance_company_id,
                                      gift_code,
                                      customer_user_id)
    end
  end
end
