# easy_bimeh_landing
#
# This file was automatically generated by APIMATIC
# v2.0 ( https://apimatic.io ).

module EasyBimehLanding
  # TravelInsurancePolicyExtend Model.
  class TravelInsurancePolicyExtend < BaseModel
    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :insurance_policy_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :travel_duration_param

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :passengers_count

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :birth_date

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :birth_date_persian

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :risk_level_discount

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :base_premium

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :all_premium

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :insurance_company_discount_rate

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :insurance_company_discount

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :insurance_centre_discount

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :coupen_discount

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :all_discount

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :exchange_premium

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :travel_rate_plan_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :plan_title

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :travel_insurance_policy_extend_ages

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :travel_insurance_policy_extend_passengers

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :zone_ids

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['insurance_policy_id'] = 'insurancePolicyId'
      @_hash['travel_duration_param'] = 'travelDurationParam'
      @_hash['passengers_count'] = 'passengersCount'
      @_hash['birth_date'] = 'birthDate'
      @_hash['birth_date_persian'] = 'birthDatePersian'
      @_hash['risk_level_discount'] = 'riskLevelDiscount'
      @_hash['base_premium'] = 'basePremium'
      @_hash['all_premium'] = 'allPremium'
      @_hash['insurance_company_discount_rate'] =
        'insuranceCompanyDiscountRate'
      @_hash['insurance_company_discount'] = 'insuranceCompanyDiscount'
      @_hash['insurance_centre_discount'] = 'insuranceCentreDiscount'
      @_hash['coupen_discount'] = 'coupenDiscount'
      @_hash['all_discount'] = 'allDiscount'
      @_hash['exchange_premium'] = 'exchangePremium'
      @_hash['travel_rate_plan_id'] = 'travelRatePlanId'
      @_hash['plan_title'] = 'planTitle'
      @_hash['travel_insurance_policy_extend_ages'] =
        'travelInsurancePolicyExtendAges'
      @_hash['travel_insurance_policy_extend_passengers'] =
        'travelInsurancePolicyExtendPassengers'
      @_hash['zone_ids'] = 'zoneIds'
      @_hash
    end

    def initialize(insurance_policy_id = nil,
                   passengers_count = nil,
                   risk_level_discount = nil,
                   insurance_company_discount_rate = nil,
                   insurance_company_discount = nil,
                   insurance_centre_discount = nil,
                   coupen_discount = nil,
                   all_discount = nil,
                   exchange_premium = nil,
                   travel_duration_param = nil,
                   birth_date = nil,
                   birth_date_persian = nil,
                   base_premium = nil,
                   all_premium = nil,
                   travel_rate_plan_id = nil,
                   plan_title = nil,
                   travel_insurance_policy_extend_ages = nil,
                   travel_insurance_policy_extend_passengers = nil,
                   zone_ids = nil)
      @insurance_policy_id = insurance_policy_id
      @travel_duration_param = travel_duration_param
      @passengers_count = passengers_count
      @birth_date = birth_date
      @birth_date_persian = birth_date_persian
      @risk_level_discount = risk_level_discount
      @base_premium = base_premium
      @all_premium = all_premium
      @insurance_company_discount_rate = insurance_company_discount_rate
      @insurance_company_discount = insurance_company_discount
      @insurance_centre_discount = insurance_centre_discount
      @coupen_discount = coupen_discount
      @all_discount = all_discount
      @exchange_premium = exchange_premium
      @travel_rate_plan_id = travel_rate_plan_id
      @plan_title = plan_title
      @travel_insurance_policy_extend_ages =
        travel_insurance_policy_extend_ages
      @travel_insurance_policy_extend_passengers =
        travel_insurance_policy_extend_passengers
      @zone_ids = zone_ids
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      insurance_policy_id = hash['insurancePolicyId']
      passengers_count = hash['passengersCount']
      risk_level_discount = hash['riskLevelDiscount']
      insurance_company_discount_rate = hash['insuranceCompanyDiscountRate']
      insurance_company_discount = hash['insuranceCompanyDiscount']
      insurance_centre_discount = hash['insuranceCentreDiscount']
      coupen_discount = hash['coupenDiscount']
      all_discount = hash['allDiscount']
      exchange_premium = hash['exchangePremium']
      travel_duration_param = hash['travelDurationParam']
      birth_date = hash['birthDate']
      birth_date_persian = hash['birthDatePersian']
      base_premium = hash['basePremium']
      all_premium = hash['allPremium']
      travel_rate_plan_id = hash['travelRatePlanId']
      plan_title = hash['planTitle']
      travel_insurance_policy_extend_ages =
        hash['travelInsurancePolicyExtendAges']
      travel_insurance_policy_extend_passengers =
        hash['travelInsurancePolicyExtendPassengers']
      zone_ids = hash['zoneIds']

      # Create object from extracted values.
      TravelInsurancePolicyExtend.new(insurance_policy_id,
                                      passengers_count,
                                      risk_level_discount,
                                      insurance_company_discount_rate,
                                      insurance_company_discount,
                                      insurance_centre_discount,
                                      coupen_discount,
                                      all_discount,
                                      exchange_premium,
                                      travel_duration_param,
                                      birth_date,
                                      birth_date_persian,
                                      base_premium,
                                      all_premium,
                                      travel_rate_plan_id,
                                      plan_title,
                                      travel_insurance_policy_extend_ages,
                                      travel_insurance_policy_extend_passengers,
                                      zone_ids)
    end
  end
end
