# easy_bimeh_landing
#
# This file was automatically generated by APIMATIC
# v2.0 ( https://apimatic.io ).

module EasyBimehLanding
  # TravelInsurancePolicyExtendView Model.
  class TravelInsurancePolicyExtendView < BaseModel
    # TODO: Write general description for this method
    # @return [TravelInsurancePolicyExtend]
    attr_accessor :travel_insurance_policy_extend

    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :travel_insurance_policy_extend_ages

    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :travel_insurance_policy_extend_passengers

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['travel_insurance_policy_extend'] = 'travelInsurancePolicyExtend'
      @_hash['travel_insurance_policy_extend_ages'] =
        'travelInsurancePolicyExtendAges'
      @_hash['travel_insurance_policy_extend_passengers'] =
        'travelInsurancePolicyExtendPassengers'
      @_hash
    end

    def initialize(travel_insurance_policy_extend = nil,
                   travel_insurance_policy_extend_ages = nil,
                   travel_insurance_policy_extend_passengers = nil)
      @travel_insurance_policy_extend = travel_insurance_policy_extend
      @travel_insurance_policy_extend_ages =
        travel_insurance_policy_extend_ages
      @travel_insurance_policy_extend_passengers =
        travel_insurance_policy_extend_passengers
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      if hash['travelInsurancePolicyExtend']
        travel_insurance_policy_extend = TravelInsurancePolicyExtend.from_hash(hash['travelInsurancePolicyExtend'])
      end
      travel_insurance_policy_extend_ages =
        hash['travelInsurancePolicyExtendAges']
      travel_insurance_policy_extend_passengers =
        hash['travelInsurancePolicyExtendPassengers']

      # Create object from extracted values.
      TravelInsurancePolicyExtendView.new(travel_insurance_policy_extend,
                                          travel_insurance_policy_extend_ages,
                                          travel_insurance_policy_extend_passengers)
    end
  end
end
