# easy_bimeh_landing
#
# This file was automatically generated by APIMATIC
# v2.0 ( https://apimatic.io ).

module EasyBimehLanding
  # InternalServer Error class.
  class InternalServerErrorException < APIException
    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :is_success

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :status

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :message

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :extra_data

    # TODO: Write general description for this method
    # @return [Exception]
    attr_accessor :exception

    # The constructor.
    # @param [String] The reason for raising an exception.
    # @param [HttpContext] The HttpContext of the API call.
    def initialize(reason, context)
      super(reason, context)
      hash = APIHelper.json_deserialize(@context.response.raw_body)
      unbox(hash)
    end

    # Populates this object by extracting properties from a hash.
    # @param [Hash] The deserialized response sent by the server in the
    # response body.
    def unbox(hash)
      @is_success = hash['isSuccess']
      @status = hash['status']
      @message = hash['message']
      @extra_data = hash['extraData']
      @exception = Exception.from_hash(hash['exception']) if hash['exception']
    end
  end
end
