# easy_bimeh_landing
#
# This file was automatically generated by APIMATIC
# v2.0 ( https://apimatic.io ).

require 'date'
require 'json'
require 'faraday'
require 'certifi'
require 'logging'

require_relative 'easy_bimeh_landing/api_helper.rb'
require_relative 'easy_bimeh_landing/easy_bimeh_landing_client.rb'

# Http
require_relative 'easy_bimeh_landing/http/http_call_back.rb'
require_relative 'easy_bimeh_landing/http/http_client.rb'
require_relative 'easy_bimeh_landing/http/http_method_enum.rb'
require_relative 'easy_bimeh_landing/http/http_request.rb'
require_relative 'easy_bimeh_landing/http/http_response.rb'
require_relative 'easy_bimeh_landing/http/http_context.rb'
require_relative 'easy_bimeh_landing/http/faraday_client.rb'

# Models
require_relative 'easy_bimeh_landing/models/base_model.rb'
require_relative 'easy_bimeh_landing/models/base_model_upload.rb'
require_relative 'easy_bimeh_landing/models/upload.rb'
require_relative 'easy_bimeh_landing/models/base_model_liability_doctor' \
                 '_insurance.rb'
require_relative 'easy_bimeh_landing/models/liability_doctor_insurance.rb'
require_relative 'easy_bimeh_landing/models/activity_area.rb'
require_relative 'easy_bimeh_landing/models/expertise.rb'
require_relative 'easy_bimeh_landing/models/commitment_ceiling.rb'
require_relative 'easy_bimeh_landing/models/insurance_company.rb'
require_relative 'easy_bimeh_landing/models/insurance_risk_level.rb'
require_relative 'easy_bimeh_landing/models/insurance_policy_term.rb'
require_relative 'easy_bimeh_landing/models/province.rb'
require_relative 'easy_bimeh_landing/models/shipping_type.rb'
require_relative 'easy_bimeh_landing/models/post_type.rb'
require_relative 'easy_bimeh_landing/models/insurance_policy_condition.rb'
require_relative 'easy_bimeh_landing/models/insurance_data_liability_doctor' \
                 '_insurance.rb'
require_relative 'easy_bimeh_landing/models/liability_doctor_insurance_policy' \
                 '_extend_view.rb'
require_relative 'easy_bimeh_landing/models/liability_doctor_insurance_policy' \
                 '_filter.rb'
require_relative 'easy_bimeh_landing/models/base_model_medical_specialties.rb'
require_relative 'easy_bimeh_landing/models/combo_data_model.rb'
require_relative 'easy_bimeh_landing/models/car_brand.rb'
require_relative 'easy_bimeh_landing/models/base_model_electronic_equipment' \
                 '_insurance.rb'
require_relative 'easy_bimeh_landing/models/car_brand_tips.rb'
require_relative 'easy_bimeh_landing/models/car_brand_tips_model.rb'
require_relative 'easy_bimeh_landing/models/has_plan.rb'
require_relative 'easy_bimeh_landing/models/electronic_equipment_insurance.rb'
require_relative 'easy_bimeh_landing/models/franchisee.rb'
require_relative 'easy_bimeh_landing/models/device_type.rb'
require_relative 'easy_bimeh_landing/models/insurance_data.rb'
require_relative 'easy_bimeh_landing/models/electronic_equipment_insurance' \
                 '_policy_extend_view.rb'
require_relative 'easy_bimeh_landing/models/electronic_equipment_insurance' \
                 '_policy_filter.rb'
require_relative 'easy_bimeh_landing/models/base_model_device_brand_types.rb'
require_relative 'easy_bimeh_landing/models/device_brand_types.rb'
require_relative 'easy_bimeh_landing/models/base_model_divice_franchisee.rb'
require_relative 'easy_bimeh_landing/models/divice_franchisee.rb'
require_relative 'easy_bimeh_landing/models/other_insurance_types.rb'
require_relative 'easy_bimeh_landing/models/send_sms_token.rb'
require_relative 'easy_bimeh_landing/models/extra_data.rb'
require_relative 'easy_bimeh_landing/models/status200.rb'
require_relative 'easy_bimeh_landing/models/get_access_token_user_info.rb'
require_relative 'easy_bimeh_landing/models/exception.rb'
require_relative 'easy_bimeh_landing/models/target_site.rb'
require_relative 'easy_bimeh_landing/models/car_brands.rb'
require_relative 'easy_bimeh_landing/models/risk_level.rb'
require_relative 'easy_bimeh_landing/models/car_uses.rb'
require_relative 'easy_bimeh_landing/models/base_model_fire_insurance.rb'
require_relative 'easy_bimeh_landing/models/fire_insurance.rb'
require_relative 'easy_bimeh_landing/models/insurance_extra_coverage.rb'
require_relative 'easy_bimeh_landing/models/insurance_extra_coverage_extra' \
                 '_data.rb'
require_relative 'easy_bimeh_landing/models/every_square_meter_coverage.rb'
require_relative 'easy_bimeh_landing/models/insurance_data_fire_insurance.rb'
require_relative 'easy_bimeh_landing/models/fire_insurance_policy_extend' \
                 '_view.rb'
require_relative 'easy_bimeh_landing/models/fire_insurance_policy_filter.rb'
require_relative 'easy_bimeh_landing/models/base_model_earthquake.rb'
require_relative 'easy_bimeh_landing/models/earthquake.rb'
require_relative 'easy_bimeh_landing/models/base_model_travel_insurance.rb'
require_relative 'easy_bimeh_landing/models/travel_insurance.rb'
require_relative 'easy_bimeh_landing/models/zone.rb'
require_relative 'easy_bimeh_landing/models/travel_duration.rb'
require_relative 'easy_bimeh_landing/models/travel_age.rb'
require_relative 'easy_bimeh_landing/models/insurance_data_travel_insurance.rb'
require_relative 'easy_bimeh_landing/models/travel_insurance_policy_extend' \
                 '_view.rb'
require_relative 'easy_bimeh_landing/models/travel_insurance_policy_extend.rb'
require_relative 'easy_bimeh_landing/models/travel_insurance_policy_filter.rb'
require_relative 'easy_bimeh_landing/models/base_model_elevator_insurance.rb'
require_relative 'easy_bimeh_landing/models/elevator_insurance.rb'
require_relative 'easy_bimeh_landing/models/elevator_type.rb'
require_relative 'easy_bimeh_landing/models/defect_organ_coverage.rb'
require_relative 'easy_bimeh_landing/models/death_capital_coverage.rb'
require_relative 'easy_bimeh_landing/models/financial_coverage.rb'
require_relative 'easy_bimeh_landing/models/medical_cost_coverage.rb'
require_relative 'easy_bimeh_landing/models/insurance_data_elevator' \
                 '_insurance.rb'
require_relative 'easy_bimeh_landing/models/elevator_insurance_policy_extend' \
                 '_view.rb'
require_relative 'easy_bimeh_landing/models/elevator_insurance_policy_filter.rb'
require_relative 'easy_bimeh_landing/models/base_model_portal_landing_page.rb'
require_relative 'easy_bimeh_landing/models/portal_landing_page.rb'
require_relative 'easy_bimeh_landing/models/insurance_group.rb'
require_relative 'easy_bimeh_landing/models/summary_card.rb'
require_relative 'easy_bimeh_landing/models/summary_notic.rb'
require_relative 'easy_bimeh_landing/models/image_album.rb'
require_relative 'easy_bimeh_landing/models/popup_image_galleryie.rb'
require_relative 'easy_bimeh_landing/models/gallery_detail.rb'
require_relative 'easy_bimeh_landing/models/video_gallery.rb'
require_relative 'easy_bimeh_landing/models/insurance_centre.rb'
require_relative 'easy_bimeh_landing/models/insurance_centre_portal.rb'
require_relative 'easy_bimeh_landing/models/extra_data_base_model_portal' \
                 '_landing_page.rb'
require_relative 'easy_bimeh_landing/models/base_model_insurance_centre' \
                 '_policy_types.rb'
require_relative 'easy_bimeh_landing/models/insurance_centre_policy_types.rb'
require_relative 'easy_bimeh_landing/models/extra_data_base_model_insurance' \
                 '_centre_policy_types.rb'
require_relative 'easy_bimeh_landing/models/base_model_damage_type.rb'
require_relative 'easy_bimeh_landing/models/damage_type.rb'
require_relative 'easy_bimeh_landing/models/insurance_types.rb'
require_relative 'easy_bimeh_landing/models/insurance_companies.rb'
require_relative 'easy_bimeh_landing/models/base_model_traking_code.rb'
require_relative 'easy_bimeh_landing/models/tracking_code.rb'
require_relative 'easy_bimeh_landing/models/tracking_damage_status_tracking' \
                 '_code.rb'
require_relative 'easy_bimeh_landing/models/tracking_damage_file_trackin' \
                 '_code.rb'
require_relative 'easy_bimeh_landing/models/tracking_damage_request.rb'
require_relative 'easy_bimeh_landing/models/tracking_damage_status.rb'
require_relative 'easy_bimeh_landing/models/tracking_damage_file.rb'
require_relative 'easy_bimeh_landing/models/tracking_damage.rb'
require_relative 'easy_bimeh_landing/models/base_model_status_status' \
                 '_collections.rb'
require_relative 'easy_bimeh_landing/models/status_status_collections.rb'
require_relative 'easy_bimeh_landing/models/base_model_status.rb'
require_relative 'easy_bimeh_landing/models/status.rb'
require_relative 'easy_bimeh_landing/models/base_model_portal_landing_contact' \
                 '_about.rb'
require_relative 'easy_bimeh_landing/models/portal_landing_contact_about.rb'
require_relative 'easy_bimeh_landing/models/insurance_centre_data.rb'
require_relative 'easy_bimeh_landing/models/base_model_faq_insurance_centre.rb'
require_relative 'easy_bimeh_landing/models/faq_insurance_centre.rb'
require_relative 'easy_bimeh_landing/models/base_model_insurance_policy' \
                 '_tracking.rb'
require_relative 'easy_bimeh_landing/models/insurance_policy_tracking.rb'
require_relative 'easy_bimeh_landing/models/base_model_special_plan.rb'
require_relative 'easy_bimeh_landing/models/special_plan.rb'
require_relative 'easy_bimeh_landing/models/extra_data_base_model_special' \
                 '_plan.rb'
require_relative 'easy_bimeh_landing/models/car_brand_model.rb'

# Exceptions
require_relative 'easy_bimeh_landing/exceptions/api_exception.rb'
require_relative 'easy_bimeh_landing/exceptions/status400_exception.rb'
require_relative 'easy_bimeh_landing/exceptions/internal_server_error' \
                 '_exception.rb'

require_relative 'easy_bimeh_landing/configuration.rb'

# Controllers
require_relative 'easy_bimeh_landing/controllers/base_controller.rb'
require_relative 'easy_bimeh_landing/controllers/file_manager_controller.rb'
require_relative 'easy_bimeh_landing/controllers/liability_doctor_insurance' \
                 '_controller.rb'
require_relative 'easy_bimeh_landing/controllers/car_body_controller.rb'
require_relative 'easy_bimeh_landing/controllers/electronic_equipment' \
                 '_insurance_controller.rb'
require_relative 'easy_bimeh_landing/controllers/other_insurance_types' \
                 '_controller.rb'
require_relative 'easy_bimeh_landing/controllers/third_party_insurance' \
                 '_controller.rb'
require_relative 'easy_bimeh_landing/controllers/motorcycle_insurance' \
                 '_controller.rb'
require_relative 'easy_bimeh_landing/controllers/fire_insurance_controller.rb'
require_relative 'easy_bimeh_landing/controllers/earthquake_insurance' \
                 '_controller.rb'
require_relative 'easy_bimeh_landing/controllers/travel_insurance_controller.rb'
require_relative 'easy_bimeh_landing/controllers/elevator_insurance' \
                 '_controller.rb'
require_relative 'easy_bimeh_landing/controllers/main_controller.rb'
require_relative 'easy_bimeh_landing/controllers/combo_data_controller.rb'
require_relative 'easy_bimeh_landing/controllers/tracking_damage_controller.rb'
require_relative 'easy_bimeh_landing/controllers/footer_controller.rb'
require_relative 'easy_bimeh_landing/controllers/insurance_policy_plan' \
                 '_controller.rb'
