# easy_bimeh_landing
#
# This file was automatically generated by APIMATIC
# v2.0 ( https://apimatic.io ).

module EasyBimehLanding
  #  easy_bimeh_landing client class.
  class EasyBimehLandingClient
    # Singleton access to file_manager controller.
    # @return [FileManagerController] Returns the controller instance.
    def file_manager
      FileManagerController.instance
    end

    # Singleton access to liability_doctor_insurance controller.
    # @return [LiabilityDoctorInsuranceController] Returns the controller instance.
    def liability_doctor_insurance
      LiabilityDoctorInsuranceController.instance
    end

    # Singleton access to car_body controller.
    # @return [CarBodyController] Returns the controller instance.
    def car_body
      CarBodyController.instance
    end

    # Singleton access to electronic_equipment_insurance controller.
    # @return [ElectronicEquipmentInsuranceController] Returns the controller instance.
    def electronic_equipment_insurance
      ElectronicEquipmentInsuranceController.instance
    end

    # Singleton access to other_insurance_types controller.
    # @return [OtherInsuranceTypesController] Returns the controller instance.
    def other_insurance_types
      OtherInsuranceTypesController.instance
    end

    # Singleton access to third_party_insurance controller.
    # @return [ThirdPartyInsuranceController] Returns the controller instance.
    def third_party_insurance
      ThirdPartyInsuranceController.instance
    end

    # Singleton access to motorcycle_insurance controller.
    # @return [MotorcycleInsuranceController] Returns the controller instance.
    def motorcycle_insurance
      MotorcycleInsuranceController.instance
    end

    # Singleton access to fire_insurance controller.
    # @return [FireInsuranceController] Returns the controller instance.
    def fire_insurance
      FireInsuranceController.instance
    end

    # Singleton access to earthquake_insurance controller.
    # @return [EarthquakeInsuranceController] Returns the controller instance.
    def earthquake_insurance
      EarthquakeInsuranceController.instance
    end

    # Singleton access to travel_insurance controller.
    # @return [TravelInsuranceController] Returns the controller instance.
    def travel_insurance
      TravelInsuranceController.instance
    end

    # Singleton access to elevator_insurance controller.
    # @return [ElevatorInsuranceController] Returns the controller instance.
    def elevator_insurance
      ElevatorInsuranceController.instance
    end

    # Singleton access to main controller.
    # @return [MainController] Returns the controller instance.
    def main
      MainController.instance
    end

    # Singleton access to combo_data controller.
    # @return [ComboDataController] Returns the controller instance.
    def combo_data
      ComboDataController.instance
    end

    # Singleton access to tracking_damage controller.
    # @return [TrackingDamageController] Returns the controller instance.
    def tracking_damage
      TrackingDamageController.instance
    end

    # Singleton access to footer controller.
    # @return [FooterController] Returns the controller instance.
    def footer
      FooterController.instance
    end

    # Singleton access to insurance_policy_plan controller.
    # @return [InsurancePolicyPlanController] Returns the controller instance.
    def insurance_policy_plan
      InsurancePolicyPlanController.instance
    end

    # Returns the configuration class for easy access.
    # @return [Configuration] Returns the actual configuration class.
    def config
      Configuration
    end
  end
end
